### ISSUE TITLE
make:content_block results to an error: No packages found ....

### ISSUE THREAD

**Issue by PKuhlmay** [FriendsOfTYPO3/content-blocks#1]
Hi I tried to test the EXT:content-blocks. Everything worked fine, but I get an error when I use the CLI command `make:content-block`.

**"No packages were found in which to store the content block."**

I am using it with ddev. Just cloned the repo and `ddev start`.

Is there a special folder structure in which the extension tries to put the new content block in?

**Comment by PKuhlmay** [comment]
I tried it in a different project where TYPO3 12 was already installed and where I have a sitepackage. There it worked but I only had the choices of the extensions "`examples` from t3docs" and "`styleguide`". I couldn't choose my sitepackage to store the new content block inside.

**Comment by nhovratov** [comment]
Hi, thanks for testing already :)
The command looks for installed extensions and then puts the new Content Block into the "ContentBlocks" folder. So make sure your extension is really installed. How does the composer.json of your sitepackage looks like?

**Comment by PKuhlmay** [comment]
This is my demo sitepackage:

```
{
    "name": "treupo/demo-site",
    "type": "typo3-cms-extension",
    "description": "",
    "homepage": "https://www.treupo.de",
    "license": ["GPL-2.0-or-later"],
    "keywords": ["TYPO3 CMS"],
    "require": {

    },
    "autoload": {
        "psr-4": {
            "Treupo\\DemoSite\\": "Classes/"
        }
    },
    "extra": {
        "typo3/cms": {
            "extension-key": "demo_site"
        }
    }
}
```

All the requirements for TYPO3 etc. are inside my root composer.json file.

**Comment by nhovratov** [comment]
Ok, weird. And the sitepackage is also visible in the extension manager?

**Comment by PKuhlmay** [comment]
It works now. Before installing the extension content-blocks I removed all other packages or third party extensions. 
I added it again and now it works. It was totally my fault 😄

**Comment by nhovratov** [comment]
Great, I'm very thankful for you testing it! Here you can find some Content Blocks examples: https://github.com/TYPO3-Initiatives/content-blocks-examples
If you have any question, you can ask me.
