### ISSUE TITLE
Make usage of icons shipped with the core

### ISSUE THREAD

**Issue by PKuhlmay** [FriendsOfTYPO3/content-blocks#100]
Hi, is it somehow possible to just use the identifiers for the icons, as used at https://typo3.github.io/TYPO3.Icons/icons/content.html

AFAIK these are allready registered and I'd like to use them.
Currently I copy the whole svg markup from that page and replace the content of Assets/Icon.svg.

It would be great if it is possible to just use something like
`icon: content-elements-searchform`
inside my EditorInterface.yaml file.

I understand if it is a lot of work to implement this but it would be a great feature.

**Comment by nhovratov** [comment]
This is a conceptual question whether we should allow this. Maybe @krausandre can say something about their early decisions. But this is my take:
- Allowing this would create 2 different possibilities to define an icon -> makes it more complicated and inconsistent.
- Adds a dependency to typo3/icons and possibly user-registered icon identifier -> can't be copied anymore.

I know that it feels wrong to have so much redundancy. However, it is actually good in this case. This issue should be rather solved in the GUI, so you can choose an SVG icon there and it will be directly copied into your folder.
