### ISSUE TITLE
Indent size of .rst files is maybe wrong

### ISSUE THREAD

**Issue by PKuhlmay** [FriendsOfTYPO3/content-blocks#116]
Hi is the indent size of **.rst** files wrong inside **.editorconfig** ??

There is: 
```
[*.{rst,rst.txt}]
indent_size = 4
```

But while editing a **.rst** file inside the Documentation folder, I realized that the current indent is 3, instead of 4. 
It seems to be sometimes 3 and sometimes 4.

**Comment by nhovratov** [comment]
Ugh, ask the documentation team. I know it was 3 originally. But was changed to 4 for easier integration of code examples. I don't know the current state.

**Comment by PKuhlmay** [comment]
Comment from Garvin in Slack:

> Indent of 4 was decided upon, its just not implemented everywhere
The new rendering draft docs covers this, and when it goes live there'll probably a "gotta catch them all" search&replace-fest.

**Comment by nhovratov** [comment]
Case closed, right?
