### ISSUE TITLE
[DOCS] command for generating language in docs is wrong

### ISSUE THREAD

**Issue by PKuhlmay** [FriendsOfTYPO3/content-blocks#117]
The command https://github.com/nhovratov/content-blocks/blob/58b656fa8e9669158a4bde5a8edbf607d131536c/Documentation/Definition/Index.rst?plain=1#L132 is wrong.

![Bildschirmfoto 2024-02-02 um 10 42 53](https://github.com/nhovratov/content-blocks/assets/107543296/a0a7ff2c-87a0-4070-a26e-59edf568a15e)

It should be `content-blocks:language:generate ` (the **s** is missing)

**Comment by nhovratov** [comment]
Fixed it as drive-by change as I was fiddling with the documentation there anyway. Sorry, I saw that you assigned this issue to yourself.

**Comment by PKuhlmay** [comment]
Its okay. I assigned it to me so you dont have to do it. But it was so small. Thanks.
