### ISSUE TITLE
Make it possible to use custom icons for collections

### ISSUE THREAD

**Issue by PKuhlmay** [FriendsOfTYPO3/content-blocks#12]
Currently a collection uses the icon `Extension.svg`. It would be great if I could use my own icons for a collection.

Maybe I could edit the yml like this:
name: treupo/collection
group: treupo
prefixFields: true
fields:
  - identifier: collection
    type: Collection
    image: collection-xy.svg
    fields:
      - identifier: text
        type: Text

And then the image is under `collection/Assets/collection-xy.svg`

Currently my collection looks like this:
![Bildschirmfoto 2023-07-03 um 17 22 05](https://github.com/nhovratov/content-blocks/assets/107543296/769820ce-bd1c-493a-8df7-79e2fb4228b7)

**Comment by nhovratov** [comment]
@PKuhlmay I implemented it a bit different. You have to place a file `{identifier.svg}` into the Assets folder. This is registered automatically then. In your example it would be `collection.svg`. This has the advantage, that it works exactly like with `Icon.svg`, but it was also easier to implement, as I could reuse the code for icon resolving.
