### ISSUE TITLE
QUESTION: custom data._processed possible?

### ISSUE THREAD

**Issue by secured** [FriendsOfTYPO3/content-blocks#130]
Just a question:

Is it possible to create your own variables under "_processed"?

**Comment by jonaseberle** [comment]
Can you give a use case?

**Comment by DanielSiepmann** [comment]
You can add your own DataProcessor before or after the `content-blocks` processor and adjust the variables. But I'm also curious about the concrete example/use case.

**Comment by secured** [comment]
The original request came when "data.CType" did not yet exist and only "data.typeName" was available.

It was confusing that "data._raw" had to be used in the template. So an integrator asked me if there was an easy way to define what is stored in "data._processed".

With version 0.5.0 this problem no longer exists. I therefore no longer have a current example.

If an additional field is added to a new content element (e.g. Author), this would presumably only be addressable via "_raw", right?
On the other hand, you would immediately see in the template that it is a special field.

Using a DataProcessor sounds like a good solution.

**Comment by DanielSiepmann** [comment]
`_processed` should contain all fields that are defined via the content block. Also processed, e.g. resolved values for relations if any processing is necessary.
`_raw` contains the raw record as fetched from the database. So `CType` and some others are special as they are very technically and probably were not considered from the beginning, which changed in recent versions.

Adding a new field, e.g. author, via the content-blocks API (the yaml form) should make it available in both, _raw and _processed.

But @nhovratov probably can provide valid proper answers here.

**Comment by nhovratov** [comment]
As Daniel already pointed out, all fields defined in YAML under `fields` will be available under `_processed`. Therefore adding fields by TCA overrides will not be included. So the question is about how to enrich the Content Block Data object with own variables. I think this will become necessary as soon as you need to calculate things in DataProcessors. Right now, this is not easily possible, as the `_processed` attribute is private and only initialized once. There are two possibilities in my opinion:

- Allow to modify ContentBlockData via DataProcessors. This method is known to integrators and developers. Could be achieved with ArrayAccess interface probably.
- Add event to ContentBlockDataDecorator. This class is responsible in wrapping the raw data in object format. Events are more developer oriented and could be foreign to integrators. However, this allows to do operations on **every** ContentBlockData wrapping. This would eliminate the need to hop over every relation by defining a condition like `if ($name === 'vendor/my-cb')`.

Would like to hear your opinions on this. This should certainly be addressed, as we have this object data specialty. Both solutions could be implemented as well for more flexibility.

**Comment by secured** [comment]
I'm not sure if this would be a good example:

```
name: psvneo/relation
title: psvneo/relation
description: 'relation'
group: common
fields:
  - identifier: 'TYPO3/Header'
    type: Basic
  - identifier: page_select
    type: Relation
    allowed: 'pages'
    maxitems: 1
    suggestOptions:
      default:
        additionalSearchFields: 'nav_title, url'
        addWhere: 'AND pages.doktype = 1'

```

"pages" provide the field "media" which is not resolved via a FilesProcessor.
Normally you would create a separate DataProcessing for the field.

```
123 = TYPO3\CMS\Frontend\DataProcessing\FilesProcessor
123 {
    as = images
    references.fieldName = media
    references.table = pages
}
```

Currently we use dataProcessing outside of _processed which works but is currently not possible otherwise.

**Comment by nhovratov** [comment]
Actually I was thinking about introducing relation resolving also for native types based on the TCA definition. We already introduced a simple TcaSchema to read TCA in a structured way. At least this problem could be resolved by that.

**Comment by tehplague** [comment]
A downside of the current overlay approach within the `ContentBlockData` class is, that "non-editor-editable" fields such as `colPos` aren't available through `data.colPos` anymore. Obviously, you wouldn't want to define colPos in the content block definition ;-)
An additional problem with this value object is that it does not implement `\ArrayAccess`. This currently breaks subsequent data processors that assume the core-shipped record array and unconditionally make array accesses. bk2k/bootstrap_package's `ContainerContextProcessor` does this, for example. In fact, I suppose almost everybody assumes `$processedData['data']` to be an array or at least to behave like one.

But at least my second problem could be easily fixed by implementing the necessary interface (as @nhovratov already pointed out).

**Comment by tehplague** [comment]
To elaborate a bit: why can't we just let `ContentBlockData::__get` fallback to `_raw` instead of immediately returning `NULL` if a key was not found in `_processed`?

**Comment by nhovratov** [comment]
@tehplague I agree we should implement ArrayAccess. I'm not sure myself, why I didn't do it. There was an issue with Fluid when the properties are not defined as class properties and no real getter exists. The magic get method didn't seem to work. The current development for v13 however will include such an object Record natively: https://review.typo3.org/c/Packages/TYPO3.CMS/+/83747 Content Blocks will probably use this (or decorate) it further.

**Comment by nhovratov** [comment]
> To elaborate a bit: why can't we just let `ContentBlockData::__get` fallback to `_raw` instead of immediately returning `NULL` if a key was not found in `_processed`?

We probably should. The thinking behind this was that system fields are normally not needed in frontend templates. So there is no need to reserve the field names. But as you said, some DataProcessors make use of them so this is a legitimate use case.

**Comment by tehplague** [comment]
We even have a case in which we need access to system fields inside the view. Some projects use Content Blocks together with containers. The templates then determine e.g. necessary responsive image breakpoints based on the fact whether a Content Block lives in a container or not and in which content column it is rendered. Hence the need for `colPos` to check if it was for a wider column or a narrow one.

As a matter of fact, @benjaminkott uses a similar approach in the Bootstrap package (see https://github.com/benjaminkott/bootstrap_package/blob/master/Resources/Private/Layouts/ContentElements/Default.html#L12). If Content Blocks were being used, this would break. I am sure there are numerous other equally valid examples for situations in which the record behind is required. I am in for the move towards value objects but this can easily be done in a backwards compatible way with regard to the use inside Fluid.

**Comment by nhovratov** [comment]
Update: The ArrayAccess interface is implemented now: https://github.com/nhovratov/content-blocks/pull/220
The ContentBlockData is now based on the new Core Record Object: https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/13.2/Index.html

So manipulating _processed would be possible now this way with a DataProcessor:

```
$data['my_var'] = 'foo';
```

In Fluid:
```
{data.my_var}
```

So no difference now to the old array structure.
