### ISSUE TITLE
Field type "Select" does not support "itemsProcConfig" setting and crashes when "items" setting is empty or missing (TYPO3 12)

### ISSUE THREAD

**Issue by tntrpsw** [FriendsOfTYPO3/content-blocks#131]
Fields of type "Select" can be configured using the setting "itemsProcFunc", but are missing a "itemsProcConfig" setting.
Note: The setting "itemsProcConfig" seems not to be mentioned in the official TYPO3 TCA Reference anymore since 11.5, but is still used within the TYPO3 core version 12.4.

Another problem seems to be, that the setting "items" can't be empty or missing. Doing so leads to an exception in the TYPO3 backend when trying to edit a content element using such configuration, at least when used within a "FlexForm" entry.

Therefore it should be possible to use the "itemsProcConfig" setting in order to pass additional parameters to a custom processing function.

A quick test by manually extending the PHP class "SelectFieldConfiguration" to regard the "itemsProcConfig" setting worked just fine.

**Comment by nhovratov** [comment]
@tntrpsw Hey, thanks for raising this issue. The documentation is correct, there is no such keyword `itemsProcConfig` in TCA. However, you can add arbitrary config keys and they will be available in the `itemsProcFunc` method. So the question is, how this should be handled. For maximum compatibility, these probably should just be carried over.

> Another problem seems to be, that the setting "items" can't be empty or missing.

This is a bug actually. Empty items should be converted to an array in FlexForm, not string.

**Comment by nhovratov** [comment]
There is now a property called `allowCustomProperties` for Select, Radio and Checkbox field types. This is an array containing additional custom properties. The default is `["itemsProcConfig"]`. Properties defined in this array will be carried over to TCA as is.
