### ISSUE TITLE
Exception after update to v0.6.0

### ISSUE THREAD

**Issue by wowaTYPO3** [FriendsOfTYPO3/content-blocks#133]
In TYPO3 12.4.11, after updating content blocks from version 0.5.2 to 0.6.0, I got the following exception in the backend:

(1/1) #1638976434 LogicException
TYPO3\CMS\Core\Cache\CacheManager can not be injected/instantiated during ext_localconf.php or TCA loading. Use lazy loading instead.

(Full stacktrace see screenshot).

Clearing the cache via the install tool does not work, manually clearing var/cache/ has no effect.

![2024-02-26_09-33-44](https://github.com/nhovratov/content-blocks/assets/343511/bbbe7b7d-186e-4cfb-a24e-1a5c1fafcbf5)

**Comment by nhovratov** [comment]
@wowaTYPO3 Oh, seems to be related to Mask being installed in parallel. Could you try to uninstall Mask?

**Comment by nhovratov** [comment]
The bug occurs when IconRegistry is instantiated in ext_localconf.php files.

**Comment by wowaTYPO3** [comment]
That doesn't change anything. I uninstalled Mask, then ran the update -> same error message.

**Comment by nhovratov** [comment]
Maybe there is another extension with IconRegistry in ext_localconf.php. Anyway this is a bug. Will have a look today.

**Comment by wowaTYPO3** [comment]
Yes, b13/container could be the one to blame.
