### ISSUE TITLE
Valid fieldtypes should be sorted alphabetical

### ISSUE THREAD

**Issue by PKuhlmay** [FriendsOfTYPO3/content-blocks#136]
When using a wrong fieldtype, you get this error: 
  ```
The type "Input" is not a valid type in Content Block "treupo/element". Valid types are: Text, Textarea, Email, Number, Link, Color, DateTime, Slug, Select, Language, Category,   
  Radio, Checkbox, Collection, File, Folder, Json, Relation, FlexForm, Password, Palette, Linebreak, Tab, Uuid.   
```

I suggest to sort this in alphabetical order.

I assume that the order comes from here: https://github.com/nhovratov/content-blocks/blob/4b9cf61eaf3044c17505004799647965e08aa859/Classes/FieldConfiguration/FieldType.php#L25

It would be easier to read, when this would be in alphabetical order.

We could discuss this in the team. It shouldn't be a big change. I could create an PR for this.

**Comment by nhovratov** [comment]
Just go for it, doesn't need to be discussed :)

**Comment by nhovratov** [comment]
However, I would just sort the output, not the order of the enums how they are defined.
