### ISSUE TITLE
[BUG][CLI] Page type make asks for content block name

### ISSUE THREAD

**Issue by benjaminkott** [FriendsOfTYPO3/content-blocks#138]
When asking the client to create a page type, it asks for a content block name.
![image](https://github.com/nhovratov/content-blocks/assets/3243119/11736e7d-b99f-4b6d-9fd9-598c8a84b174)

**Comment by nhovratov** [comment]
This is correct, as every Content Block has a unique identifier (=name).

**Comment by benjaminkott** [comment]
I think you are getting me wrong here. I would expect to ask me for the name of the page-type and not the content-block name.

**Comment by nhovratov** [comment]
Well, technically a page type is a Content Block. Of course we could change the question depending on the type. But were you really confused because of that?

**Comment by benjaminkott** [comment]
Yes, I restarted the process multiple times and checked for errors. It would help if the "content block" is just removed from that step.

**Comment by nhovratov** [comment]
I added "Content Block" there, so the user knows it's **not** about the human-readable title. Maybe "name" was poorly chosen. Maybe you could give us a hint on how to formulate it best. Also with the background of adding a question for the title.
