### ISSUE TITLE
[BUG][CLI] Default value "Content Element" is not matched by options

### ISSUE THREAD

**Issue by benjaminkott** [FriendsOfTYPO3/content-blocks#139]
The default option for the create command is not matched by options.

"Content Element" -> "content-element"

![image](https://github.com/nhovratov/content-blocks/assets/3243119/31806f00-e94b-4fed-bbea-2dcc84b48710)

**Comment by nhovratov** [comment]
This is the way symfony displays the default value. Not the internal identifier, but the label from the options. If you press enter with nothing typed in, it will correctly choose Content Element as the default.

**Comment by benjaminkott** [comment]
ack
