### ISSUE TITLE
[FEATURE][CLI] Add hint that "Records" need to be created in a folder within TYPO3.

### ISSUE THREAD

**Issue by benjaminkott** [FriendsOfTYPO3/content-blocks#142]
Since ages we as experienced developers are used to that we need to lift the restriction of Records to also allow them to be created on the root level or page level. But this is also confusion for new users. Please add a hint, that newly created Records must be created on a page in the backend, or configured otherwise - maybe also add it to the wizard.

**Comment by nhovratov** [comment]
This is documented. But yeah, we could also pre-configure them to be allowed on normal pages. If this is best practive and the folder restriction is nonsensical by now.
