### ISSUE TITLE
Pagetypes problem while using FlexForm

### ISSUE THREAD

**Issue by miroslavborecky** [FriendsOfTYPO3/content-blocks#143]
Hello,
I have been working on project and as I wanted to use Flexform in Pagetype i came around this error `TYPO3\CMS\ContentBlocks\Definition\FlexForm\FlexFormDefinition::setTypeName(): Argument #1 ($typeName) must be of type string, int given`
because FlexFormDefinition.php requires TypeName as "string"  but  PageDoktypeRegistry.php requires TypeName as "integer", so it seems there is no valid option for using FlexForms in pagetypes.
Thank you for your response in advance.

**Comment by nhovratov** [comment]
I will have a look, thanks for the report!

**Comment by nhovratov** [comment]
@miroslavborecky Released version 0.6.3, have fun!

**Comment by miroslavborecky** [comment]
@nhovratov Thank you.
