### ISSUE TITLE
[BUG] Overlay Relations are not resolved correctly

### ISSUE THREAD

**Issue by CKussin** [FriendsOfTYPO3/content-blocks#144]
Imagine the following content block hierarchy:

Content Element (File: ce.yaml)
   Collection: Record Type (File: rt.yaml)
      Category

In the global language (0) anything is working like charm. But with a localized content element, the resolution of references in respect to the language won't work.
Only the categories of the base record (sys_language_uid = 0) are resolved. So if the localization differs from the base element, the base categories are loaded.

I traced it down to the \TYPO3\CMS\ContentBlocks\DataProcessing\RelationResolver.
The function getUidOfCurrentRecord don't take _LOCALIZED_UID or _PAGES_OVERLAY_UID into account.XClassing and overwriting the functions seems to work (for now) but i think this is not an intended behavior.

[bug_relation.zip](https://github.com/nhovratov/content-blocks/files/14506886/bug_relation.zip)

**Comment by nhovratov** [comment]
@CKussin Would you like to provide a PR for the change? Or at least show the diff, what you've changed? Anyway, thanks for the report!

**Comment by CKussin** [comment]
Of course,

this is what i've done:

` class RelationResolver extends \TYPO3\CMS\ContentBlocks\DataProcessing\RelationResolver
{
    protected function processCategory(
        TcaFieldDefinition $tcaFieldDefinition,
        ContentTypeInterface $typeDefinition,
        string $parentTable,
        array $record
    ): array {

        $tcaFieldConfig = $this->getMergedTcaFieldConfig($parentTable, $tcaFieldDefinition, $typeDefinition);
        $uidList = $tcaFieldConfig['config']['relationship'] === 'manyToMany' ? '' : (string)($record[$tcaFieldDefinition->getUniqueIdentifier()] ?? '');

        $result = $this->getRelations(
            uidList: $uidList,
            tableList: $tcaFieldConfig['config']['foreign_table'] ?? '',
            mmTable: $tcaFieldConfig['config']['MM'] ?? '',
            uid: $this->getUidOfCurrentRecord($record, true),
            currentTable: $parentTable,
            tcaFieldConf: $tcaFieldConfig['config'] ?? []
        );
        return $result;
    }

    protected function getUidOfCurrentRecord(array $record, bool $considerOverlay = false): int
    {
        if (isset($record['_ORIG_uid'])) {
            return (int)$record['_ORIG_uid'];
        }
        if ($considerOverlay && isset($record['_LOCALIZED_UID'])) {
            return (int)$record['_LOCALIZED_UID'];
        }
        return (int)$record['uid'];
    }
}
`

it's just a very localized fix.

**Comment by nhovratov** [comment]
@CKussin Is the category you reference translated into the target language?

**Comment by CKussin** [comment]
The category is and so is the RecordType holding the reference. But if the category is translated or not seems to have no effect on the result. As the reference to a category is always to the untranslated entry.

The problem is, as far as i can tell, that for the resolution of the category references the uid of the untranslated (in this case record type) is used.

**Comment by nhovratov** [comment]
The normal procedure is: first get the record in the default language, and then do overlays. Maybe it's different for MM records and/or with allowLanguageSynchronization. Need to dig deeper here.

So what would also be interesting for me is:
- Site config for translations
- Translation behaviour ("custom value", or "value of default record")

Some screenshots would also be helpful.
I investigate the issue further in parallel. Any additional hint would be appreciated.

**Comment by nhovratov** [comment]
I believe your fix was correct. I had something simillar also in EXT:mask. Seems it only is a problem with MM relations.
