### ISSUE TITLE
[QUESTION] Change PageType Template

### ISSUE THREAD

**Issue by PLACEBOBRO** [FriendsOfTYPO3/content-blocks#146]
Hi,
I added a new PageType ("Magazine") via Content-Blocks. Under Resources/Private/Templates all my Page Templates are located.
![image](https://github.com/nhovratov/content-blocks/assets/40799248/7620ba18-717b-487f-9a40-8b2c60df0d88)
Now if I look at the frontend the Subpage.html is used instead of the Magazine.html.
My PageType EditorInterface.yaml looks like this:
![Bildschirmfoto 2024-03-08 um 10 12 28](https://github.com/nhovratov/content-blocks/assets/40799248/6c869e0f-11dc-4d4d-874b-f1390720828b)
I tried to add a Frontend.html to the Source folder in my PageType but that doesn't work.
Do I miss an option where I can define which template should be used in my PageType? I didn't find anything in the documentation ...

**Comment by nhovratov** [comment]
@PLACEBOBRO Hi, first of all thanks for trying out Content Blocks!
So, in regard to Page Types there is still documentation missing on how to use in in the frontend. This will be added soon!

> I tried to add a Frontend.html to the Source folder in my PageType but that doesn't work.

The Frontend.html does only work for Content Elements. For Page Types the template has to be defined outside.

To use your custom Page Types as Frontend templates, you need to connect them via TypoScript in your PAGE object.
You probably have something like this but with the key `layout`, so the template depends on the backend layout. I recommend to change this to the doktype switch, as this way easier to understand, also for editors. If you have a special layout for the Homepage, you can also create a new Page Type for it.

```
page = PAGE
page {
  10 = FLUIDTEMPLATE
  10 {
    templateName = TEXT
    templateName {
      cObject = CASE
      cObject {
        key.field = doktype

        default = TEXT
        default.value = Subpage

        117 = TEXT
        117.value = Magazine
      }
    }
```

**Comment by PLACEBOBRO** [comment]
Thank you very much. That worked out for me!

**Comment by nhovratov** [comment]
@PLACEBOBRO One more thing. In order to benefit from Content Blocks processing also for Page Types, you need to add the DataProcessor. This means, if you have relations like Files in your Page Types, you don't need to worry about adding FilesProcessors and stuff.

```
page = PAGE
page {
  10 = FLUIDTEMPLATE
  10 {
    dataProcessing {
      1 = content-blocks
```
