### ISSUE TITLE
Exception in page view

### ISSUE THREAD

**Issue by fe-mohmand** [FriendsOfTYPO3/content-blocks#160]
We have updated to the newest version of content blocks and TYPO3 12.4.13.
We are getting now backend exception after clicking on a random site in the page view.

![exception_page](https://github.com/nhovratov/content-blocks/assets/131554515/bd084655-1337-4f3e-b2aa-c14ecba4e279)

I have removed our content elements without success.

**Comment by fe-mohmand** [comment]
I have installed now version 0.6.4 and getting now exception in frontend and when running cli  **typo3 cache:flush**

```
[ TYPO3\CMS\Core\Error\Exception ]
  PHP Warning: Array to string conversion in /var/www/html/vendor/contentblocks/content-blocks/Classes/Loader/LoadedContentBlock.php line 47
```

**Comment by nhovratov** [comment]
@fe-mohmand Thanks for the bug report. The first error seems to be legit. The second one is probably due to wrong cache entries from the main branch. So just delete everything in var/cache and it should work again.
