### ISSUE TITLE
Subfolder resolution in Basics folder

### ISSUE THREAD

**Issue by CKussin** [FriendsOfTYPO3/content-blocks#161]
It seems this is currently not supported.
For better structuring this would be nice to at least create one level of subfolders.

tx_ext/ContentBlocks/Basics/Root/base.element.yaml
tx_ext/ContentBlocks/Basics/tx_element.yaml

If you can give me a hint where i can adapt this by my self than i will do it.

**Comment by CKussin** [comment]
Found the location of the restriction:

In \TYPO3\CMS\ContentBlocks\Basics\BasicsLoader->loadUncached() the depth() function on the finder can be removed.
the basic-identifier is the key to store so no harm on that side.

I try it on a larger scale and report back

**Comment by CKussin** [comment]
Pull request:

#162

**Comment by nhovratov** [comment]
Yeah, I think we can do this if this helps with structuring. We didn't think this would be used this extensively so one level seemed enough.

**Comment by nhovratov** [comment]
Merged.
