### ISSUE TITLE
Linbreaks automagically exclude if not within palette

### ISSUE THREAD

**Issue by CKussin** [FriendsOfTYPO3/content-blocks#164]
I have a few basics and want to share as much stuff as possbile (i want a clean api and as much reusability as possible).
Now i have the problem that i have to duplicate some field basics in order to support the fields within the palette as well as outside.

Perhaps a setting on the Basic FieldType like "assetIfNotInPalette" would be helpful.

What do you think?

I prepare a pr for this issue.

**Comment by nhovratov** [comment]
So you mean instead of disallowing Linebreaks outside of palettes, you want them to be ignored?

**Comment by CKussin** [comment]
Yeah pretty much. But only if explicitly set for better understanding.

**Comment by nhovratov** [comment]
Okay, I think we can do that. It's interesting how you make use of Basics we didn't even think of. Thanks for the feedback and PRs so far, this really helps everyone!

**Comment by CKussin** [comment]
PR: #165 

No documentation included cause the field name is up to you guys.

**Comment by CKussin** [comment]
> Okay, I think we can do that. It's interesting how you make use of Basics we didn't even think of. Thanks for the feedback and PRs so far, this really helps everyone!

Thanks for all your work. This system is awesome! a big step in the typo3 way of doing things!
And if i can contribute and help, it's a pleasure.

**Comment by nhovratov** [comment]
Merged.
