### ISSUE TITLE
PageView breaks when using field type: Folder in version 0.6.0 or newer

### ISSUE THREAD

**Issue by kuepper-faktor-e** [FriendsOfTYPO3/content-blocks#172]
When using the field type Folder in version 0.6.0 or newer (where Symfonys VarExporter is used), the PageView breaks when there's at least one folder selected in the content element. The VarExporter tries to iterate over all the files/object aggregated from the folder(s). 

To reproduce just configure a content element with a field using the type Folder. Then create a record of this content element and select at least one non-empty folder from the file list. 

`
name: some-vendor/photo-gallery
group: common
prefixFields: true
prefixType: vendor
basics:
  - TYPO3/Access
fields:
  -
    identifier: header
    useExistingField: true
    required: true
  -
    identifier: gallery
    type: Folder
`

Error message: 

`Type "Closure" is not instantiable.`

I've to admit I didn't digged deep enough yet to say the exact point where this breaks, but as the Exporter iterates recursively over  all the resource file objects and its relations, there are several points where Closures are used. 

Just a short overview from the stack trace, on which the prepare-Method is called from the Exporter: 
TYPO3\CMS\Core\Resource\File -> TYPO3\CMS\Core\Resource\AbstractFile -> TYPO3\CMS\Core\Resource\ResourceStorage -> TYPO3\CMS\Core\EventDispatcher\EventDispatcher -> TYPO3\CMS\Core\EventDispatcher\ListenerProvider -> Symfony\Component\DependencyInjection\Container -> _early.Composer\Autoload\ClassLoader -> TYPO3\CMS\Core\DependencyInjection\ServiceProviderRegistry

**Comment by wowaTYPO3** [comment]
Same problem here with content_blocks 0.6.4
