### ISSUE TITLE
Support overrideChildTca for FileFieldType

### ISSUE THREAD

**Issue by justusmoroni** [FriendsOfTYPO3/content-blocks#179]
It seems to me that we can't define `overrideChildTca` for the File field types.

As far as i can see there is no support for `overrideChildTca` in `Classes/FieldType/FileFieldType.php` at the moment but it exists in `Classes/FieldType/CollectionFieldType.php`.

Another thing to note is that it could be overwritten by `extendedPalette` which is true by default.
```
        if (!$this->extendedPalette) {
            $config['overrideChildTca'] = [
                'types' => [
                    AbstractFile::FILETYPE_IMAGE => [
                        'showitem' => '--palette--;;basicoverlayPalette,--palette--;;filePalette',
                    ],
                    AbstractFile::FILETYPE_AUDIO => [
                        'showitem' => '--palette--;;basicoverlayPalette,--palette--;;filePalette',
                    ],
                    AbstractFile::FILETYPE_VIDEO => [
                        'showitem' => '--palette--;;basicoverlayPalette,--palette--;;filePalette',
                    ],
                ],
            ];
        }
```

In my use case i want to use the sys_file_references but want to define the `showitem` string myself.

Maybe we could allow it and merge the arrays after the data that was provided by `extendedPalette`.

**Comment by nhovratov** [comment]
Hey, thanks for the feature request! Right now you could already do this by using TCA/Overrides. We will think about a solution, but we specifically don't want the showitem syntax to appear in the YAML file.

**Comment by nhovratov** [comment]
I've added now overrideChildTca as allowed properties for type File. This is a valid bugfix by itself. Of course we could think about a feature to easily define alternative showitems (=fields array) for Collection sub-types. But right now we have a feature freeze, as the Core patch is now being worked on.
