### ISSUE TITLE
Typos with umlauts are not handled correctly.

### ISSUE THREAD

**Issue by PKuhlmay** [FriendsOfTYPO3/content-blocks#182]
When I have a typo (not TYPO3 😆) with an umlaut (ä, ö, ü) inside the human-readable title while creating a record type inside the CLI, and then remove the typo, the name is not handled correctly.

I get the following weird name:

![Bildschirmfoto 2024-04-12 um 15 53 36](https://github.com/nhovratov/content-blocks/assets/107543296/1f6eab70-eb87-4274-908e-50c0ab86df16)

Inside the locallang.xlf:
```
<trans-unit id="title" resname="title">
     <source>Rel�ations test</source>
</trans-unit>
```

Steps to reproduce:
* Create a new content element inside the CLI
* Choose record type (I assume it is the same for page type and content element)
* set your properties (vendor and identifier)
* Set a human-readable name like this.
  * type `Relä`
  * hit the delete key to remove the umlaut.
  * type `ations`

In the CLI the name should be now `Relations` but when you save it and go to the backend to use your element, the name is `Rel�ations test`

_I don't know if this is related to the CB, especially the CLI command for creating an element._

**Comment by nhovratov** [comment]
I suppose removing one character just removes 1 byte instead of 2 bytes for utf-8 characters, so you end up with a broken byte.

**Comment by PKuhlmay** [comment]
Is There something we can do about it? I mean the cli command and the content block are working, it only looks a little bit strange.

**Comment by nhovratov** [comment]
I don't think **we** can. This is an underlying issue in symfony console (?). This is beyond my level of expertise tbh.

**Comment by jonaseberle** [comment]
I think this has nothing to do with Content Blocks or even Symfony – that terminal just does not handle multibyte well ;) 

Can you try another one?
I cannot reproduce on my systems.
