### ISSUE TITLE
Extending Content Blocks Palettes/Basics

### ISSUE THREAD

**Issue by fe-brauer** [FriendsOfTYPO3/content-blocks#183]
Hi there,

first of all: I really like content-blocks. 
For me, as an Integrator, the creation of content elements got so much easier, thank you for your great work!

That being said, i currently have a minor problem.

I defined a custom field in my TCA. This field should be visible inside the "appearance" - Tab after the "space_after_class" dropdown.

Now, should I copy the YAML from TYPO3/Appearance and define my own Basic to add this field or is there an easier way, which I was unable to find in the docs?

Any kind of hint would be helpful :)

Kind regards,
Christoph

**Comment by nhovratov** [comment]
@fe-brauer Thanks for your feedback, I'm glad you like it! You actually answered the question to yourself already. Yes, just copy the Appearance Basic YAML from Content Blocks and adjust it to your specific needs. Right now, there are no overrides possible for YAML. The strategy is: Copy what you need and adjust it. For small, individual adjustments TCA overrides are always possible, if copying is not applicable.

**Comment by fe-brauer** [comment]
@nhovratov thank you for the answer. Then i will simply copy and adapt :)
