### ISSUE TITLE
Inline children ignore enablecolumns after flushing all caches

### ISSUE THREAD

**Issue by ri-klein** [FriendsOfTYPO3/content-blocks#185]
Hello,
I noticed some weird behavior with child records from `type: Collection` fields in content blocks of type content-element. After upgrading from version 0.6 to 0.7 (on a TYPO3 12.4.14 instance), the TCA `enablecolumns` of those child records seem to be ignored for the first request after flushing all caches (meaning hidden / time restricted / group restricted records show up in frontend).

I was able to reproduce the issue on another TYPO3 12 instance that never had content-blocks installed before (so we can probably exclude 'leftovers' from the old version). To reproduce it, I did the following steps:

- I created a small test extension called `testcb`, just for the content block
- Then I created a new content block via CLI with the following command:
```
ddev typo3 content-blocks:create --content-type="content-element" --vendor="riklei" --name="testcb" --title="Test Content Block" --extension="testcb"
```
- I set the content block EditorConfig to this:
```
name: riklei/testcb
typeName: riklei_testcb
group: common
prefixFields: true
prefixType: full
fields:
  - identifier: children
    type: Collection
    labelField: title
    fields:
      - identifier: title
        type: Text
```
- In the backend, I created a new content element with the following child records (see image below):
  - test1 and test2: normal elements supposed to be visible
  - test hidden: `hidden` set to 1
  - test expired: `endtime` set to some past date
  - test group access: `fe_group` set, so not-logged in users can't see the record

![content_element](https://github.com/nhovratov/content-blocks/assets/144095794/15b70b29-2909-4c39-812c-d241a9a9a583)

- I flushed the caches via CLI `cache:flush` command (though the backend 'flush all caches' option works too)
- Printing out the data array after the first request shows, that it contains all 5 child records, even though only 2 are supposed to show up

![data_array_after_cache_flush](https://github.com/nhovratov/content-blocks/assets/144095794/802a0e88-fb2b-4aa8-80ce-ec7d091e8f38)

- Upon Reloading the page, only the correct records show up

![data_array_second_request](https://github.com/nhovratov/content-blocks/assets/144095794/6c141a97-714f-4fa6-8049-ee381652e94a)

- This can be repeated; After flushing the caches all 5 records show up again for the first request

During testing how to reproduce the issue I noted the following things:
- The issue does not seem to show up when pressing the 'view' button in backend
- It does not matter if the first request after flushing the caches happens on a page with the content block on it or not; From the second request on it works correctly

I did some digging on the issue. It seems that the culprit is the class `TYPO3\CMS\ContentBlocks\Schema\SimpleTcaSchemaFactory`. It gets instantiated via Dependency Injection, but apparently at a time before the TCA definitions for the auto-created content blocks tables are set in `$GLOBALS['TCA']`. This means the internal `$tca` array is missing those definitions, and when `\TYPO3\CMS\ContentBlocks\DataProcessing\RelationResolver::getRelations()` then checks if the table definition exists, it (wrongly) returns false, and the additionalWhere does not get set correctly. I guess on subsequent requests the TCA definitions get fetched from cache, which is why it then works correctly.

This is just an educated guess though; I don't understand the code base well enough to comfortably say that this is DEFINITELY the issue. So feel free to correct me on that.

**Comment by nhovratov** [comment]
@ri-klein Hey, thanks for the detailed issue description! You might be on to something. I will have a look soon.
