### ISSUE TITLE
Translation of "inline" ContentElement list

### ISSUE THREAD

**Issue by CKussin** [FriendsOfTYPO3/content-blocks#191]
I have a strange behavior. I have a RecordType holding Inline Content Elements. This RecordType is inlined in a ContentElement itself.

On translating the page everything falls apart.
The inline content elements can be selected in the translation wizard. after the wizard the inline elements appear in the colPos and the record type throws an undefined error on showing.

Something i miss? This should be a valid configuration i think. seems like on the translation the inline content elements "loos" their connection to the parent record element.

**Comment by CKussin** [comment]
some additional info

Error in LOG:
  | Core: Exception handler (WEB): Uncaught  TYPO3 Exception: Call to a member function isCustomState() on null \|  Error thrown in file  /var/www/html/typo3_src-12.4.11/typo3/sysext/backend/Classes/Form/FieldWizard/LocalizationStateSelector.php  in line 97. Requested URL:  http://docker.local-instance.com/typo3/ajax/record/inline/details?token=--AnonymizedToken--
-- | --

Screenshot of the Inline Element in BE (notice the undefined State of the translation behavior field)
![grafik](https://github.com/nhovratov/content-blocks/assets/49631108/4d9721c9-1158-4f0b-9ae2-be4fdbad0b1b)

**Comment by CKussin** [comment]
Okay i figured out, that the problem was a wrong config in the record type. there i used the translation behavior aswell and that's - let's phrase it this way - not goood!!

But the filter in the translation wizard should be applied. so that every "inline" item will be removed from the list

**Comment by CKussin** [comment]
Solved this issue for now:

I overwrote the \TYPO3\CMS\Backend\Controller\Page\LocalizationController->getRecordLocalizeSummary function and filtered all elements out that have a "foreign_table_parent_uid" > 0.

I hope this helps to other people

**Comment by CKussin** [comment]
Found an even better solution: Overwrite the LocalizationRepository->getRecordsToCopyDatabaseResult function and do the same stuff. this way the copy function also works as intended

**Comment by nhovratov** [comment]
@CKussin Hey Christopher, this is a really nice finding, thank you so much for reporting and digging deeper. Of course we can't just override a Core class in Content Blocks, so I added an EventListener to filter out children. Maybe we can provide another event in Core so we can filter them out while fetching from DB already. This will simplify things a lot.

**Comment by CKussin** [comment]
> @CKussin Hey Christopher, this is a really nice finding, thank you so much for reporting and digging deeper. Of course we can't just override a Core class in Content Blocks, so I added an EventListener to filter out children. Maybe we can provide another event in Core so we can filter them out while fetching from DB already. This will simplify things a lot.

An even better solution i think. My understanding of the typo3 mechanics are still beginner level so this options didn't came to my mind 😆
