### ISSUE TITLE
directory "config" a mistake?

### ISSUE THREAD

**Issue by georgringer** [FriendsOfTYPO3/content-blocks#20]
I don't know from reading why there is this config directory inside the root of the extension? if this is for testing, maybe this should be copied using a composer `post-autoload-dump` command to copy it from the build directory but by default it feels very wrong seeing this dir

**Comment by nhovratov** [comment]
Yes, this is for developing so you have default configuration for a ddev based TYPO3 instance. I would be fine with it being copied and ignored by git when running composer install. Do you have an example, where this is done?

**Comment by georgringer** [comment]
we do something like this for .env files on local machines, to copy the env.local to .env. same could be done to copy the dir from e.g. the build directory

```json
"scripts": {
    "pre-autoload-dump": [
      "@php -r \"file_exists('.env') || copy('.env.local', '.env');\""
    ],
```

**Comment by jonaseberle** [comment]
We can have an `export-ignore` in the `.gitattributes` which prevents the dirs from being included in the .zip-dists (thus also in a normal composer install).

As an example https://github.com/dmind-gmbh/extension-cookieman/blob/master/.gitattributes

**Comment by jonaseberle** [comment]
Yes, like https://github.com/nhovratov/content-blocks/issues/21 ;)

**Comment by nhovratov** [comment]
@jonaseberle I think this is still nice for the TER release. If we publish with tailor, some folders are excluded by default: https://github.com/TYPO3/tailor/blob/main/conf/ExcludeFromPackaging.php
But no the config folder.
