### ISSUE TITLE
Category Field in RecordType not working in Translation

### ISSUE THREAD

**Issue by CKussin** [FriendsOfTYPO3/content-blocks#204]
Hey,

something odd is happening. I have a record type, holding a category field. On the Global(0) Language everything is working as expected. But on the translated pages the category field is not loaded correctly.

Any ideas ?

best regards

**Comment by nhovratov** [comment]
Is the category translated?

**Comment by CKussin** [comment]
yes they are.

**Comment by CKussin** [comment]
little addition here. the page is in free mode if this has anything to do with this

**Comment by nhovratov** [comment]
Ok, I will try to reproduce this.

You have the latest version I suppose?
Is the category stored inside the root page?

**Comment by CKussin** [comment]
Ah sorry for the late response.

The latest version? Yes
Category stored inside of a root page yes but not 0.

The same "problem" happens to occur in content element references.

**Comment by nhovratov** [comment]
Hey, I couldn't reproduce this issue. My category field is loaded correctly in the backend in a translated record. Could you provide your configuration?

**Comment by nhovratov** [comment]
Relation resolving is now based on Core feature. This won't be further investigated for the v12 version. If you encounter this problem in v13, please create a forge ticket.
