### ISSUE TITLE
Undefined TranslationState in IRRE Element

### ISSUE THREAD

**Issue by CKussin** [FriendsOfTYPO3/content-blocks#207]
Hey,

me again.
I have weird behavior - or to be precise - no behavior @all

![grafik](https://github.com/nhovratov/content-blocks/assets/49631108/d9d8e83f-0848-464e-9ec9-4c74646a63ed)

This is a irre element within a contentElement. The Field holding the irre itself is marked with 
`    
behaviour:
      allowLanguageSynchronization: true
`

But the state is undefined - whatever i do. Even explicitly stating to use the custom value don't have any influence of the state

**Comment by nhovratov** [comment]
What do you expect here to happen? I'm not sure how allowLanguageSynchronization should exactly work with IRRE elements. Maybe you are looking for this option: `showAllLocalizationLink` https://docs.typo3.org/m/typo3/reference-tca/main/en-us/ColumnsConfig/Type/Inline/Properties/Appearance.html#confval-inline-appearance

**Comment by nhovratov** [comment]
This could have something to do with: https://github.com/nhovratov/content-blocks/issues/238

**Comment by timwehrmann** [comment]
Stumbling from #238 into this issue: Might be possible. But I do not get the original request. Being more precise on that: What the expected backend behavior should be in this case. Maybe @CKussin can help out with further explanation. :)

**Comment by nhovratov** [comment]
It's weird that the LocalizationStateSelector is rendered without an error as opposed to the newer reported issue. But I suppose it is the same problem after all.

**Comment by nhovratov** [comment]
@CKussin Released a bugfix version. This should work now.
