### ISSUE TITLE
QUESTION: How to use code blocks withTYPO3 v. 13.2.0?

### ISSUE THREAD

**Issue by bzimm16** [FriendsOfTYPO3/content-blocks#212]
I would like to use TYPO3 v13 for a new project. How can I use "content blocks"? The extension only works up to T3 v12 according to ext_emconf and it does not seem to be included in v13 yet.

**Comment by nhovratov** [comment]
Please be patient. We will release a v13 compatible version soon.

**Comment by bzimm16** [comment]
Thank you for your quick answer.

But does this mean, that if I want to start working on my project now, I have to start it in v12 and then upgrade?

**Comment by nhovratov** [comment]
If you really really need it right now, you can checkout the v13 branch: https://github.com/nhovratov/content-blocks/tree/typo3-v13

**Comment by bzimm16** [comment]
Thanks. Is it safe to use the v13 branch? Do you have an idea when you release it? I am just trying to plan my project and as I have deadlines I do not want to run to a dead end

**Comment by nhovratov** [comment]
The branch is exactly what I want to release. Plus some refactoring by using new features introduced in v13.2.

**Comment by nhovratov** [comment]
Content Blocks v0.8.0 is released which supports TYPO3 v13.
