### ISSUE TITLE
dev mode (DDEV): Dependency Injection

### ISSUE THREAD

**Issue by jonaseberle** [FriendsOfTYPO3/content-blocks#216]
I am getting 
```
Cannot autowire service "TYPO3\CMS\ContentBlocks\UserFunction\ContentWhere": argument "$parentFieldNames" of method "__construct()" is type-hinted "  
  array", you should configure its value explicitly.     
```

when I run `typo3 cache:warmup` in dev mode with DDEV (`composer install` on this repo)

with TYPO3 13.2.1

Should we exclude `\TYPO3\CMS\ContentBlocks\UserFunction\ContentWhere` from autowiring in `Services.yaml`?

```
  TYPO3\CMS\ContentBlocks\UserFunction\ContentWhere:
    autoconfigure: false
```
works (but `autowire: false` does, too and I can never remember which one is correct in this case)

**Comment by nhovratov** [comment]
@jonaseberle This has something to do with https://forge.typo3.org/issues/104345
Due to this, the root package is not included anymore, so Content Blocks is not loaded with DI.

**Comment by nhovratov** [comment]
main branch is raised to dev-main of TYPO3.
