### ISSUE TITLE
Question: Pass constants to content blocks

### ISSUE THREAD

**Issue by MAVEO-ps** [FriendsOfTYPO3/content-blocks#224]
Hey,

I'm trying to use constants inside my content blocks, but I can't get it to work.

For example I have defined one as follows:
sitepackage.graphics {
    graphicOne = fileadmin/graphics/graphic-element-1.svg
}

In my page-template Default.html I am able to use the constant and I get all content blocks as follows:
<f:for each="{mainContent}" as="contentElement">
     <f:cObject typoscriptObjectPath="tt_content.{contentElement.data.CType}" data="{contentElement.data}" table="tt_content"/>
</f:for>

But inside the Frontend.html of the content blocks I am trying to to use <f:cObject typoscriptObjectPath="lib.inlineSvg" data="{src: settings.sitepackage.graphics.graphicOne}" /> but it is not working because settings.sitepackage.graphics.graphicOne ist not defined. I get that I have to pass the argument somehow, but I don't get how to do it. 

Am I missing something or is it just not possible to use constants inside the Frontend.html?

Thank you all very much for your help!

**Comment by nhovratov** [comment]
You have to provide your settings to the lib.contentBlock FLUIDTEMPLATE object just like for your main template.

This should work:

```
lib.contentBlock {
    settings =< settings.sitepackage
}
```

**Comment by MAVEO-ps** [comment]
Thank you very much!

Unfortunately, your code did not work, but if I pass the constants individually like this, it works:
lib.contentBlock {
    settings.sitepackage.graphics {
        graphicOne = {$sitepackage.graphics.graphicOne}
    }
}

 Now I know where to start and see if I can find a better solution and pass all constants  at one.

**Comment by nhovratov** [comment]
Great! It depends on how you've defined your settings. Maybe it can be found in:

page.10.settings or something similar.

**Comment by viu-x** [comment]
For anyone interested… I stumbled upon this issue and tried to implement it as suggested and did use the `SiteDataProcessor` in the end. Makes the whole Site-Object available and therefore all site settings as well.

```
lib.contentBlock {
  dataProcessing {
    20 = site
  }
}
```
