### ISSUE TITLE
Nested Content Elements gets rendered twice when using standard CE's

### ISSUE THREAD

**Issue by Mo310794** [FriendsOfTYPO3/content-blocks#226]
Hey,

When I followed the "Nested Content Elements" chapter in the documentation, I encountered the following behavior:

As described in the documentation, I created the Tabs content element. The only difference from the documentation is that I added a textmedia CType to the Tabs content element.

![image](https://github.com/user-attachments/assets/55064de7-263d-4c05-ba3e-8c2f4c54debb)

**Comment by nhovratov** [comment]
Hey, if you don't built upon styles.content.get you need to restrict your frontend queries. I don't know what you are using to render the columns. If you use TypoScript you can add the postUserFunc from Content Blocks directly:

https://docs.typo3.org/p/contentblocks/content-blocks/main/en-us/Guides/NestedContentElements/Index.html#preventing-output-in-frontend

**Comment by nhovratov** [comment]
Example:

```
    20 = CONTENT
    20 {
        table = tt_content
        select {
            includeRecordsWithoutDefaultTranslation = 1
            orderBy = sorting
            where = {#colPos}={register:colPos}
            where.insertData = 1
            where.postUserFunc = TYPO3\CMS\ContentBlocks\UserFunction\ContentWhere->extend
            pidInList.data = register:pageUid
            pidInList.override.data = register:contentFromPid
        }
        stdWrap {
            dataWrap = {register:wrap}
            required = 1
        }
    }
```

**Comment by Mo310794** [comment]
Thanks, after I added your Example it worked.
