### ISSUE TITLE
Adding Logic

### ISSUE THREAD

**Issue by dpolakovics** [FriendsOfTYPO3/content-blocks#230]
Hello,

through the typo3 news i came across this nice project.
As I'm looking into it I have the following question:

Is there anything planned like having a [list,single] view content element of record types?
I think that would be very helpful to transition from extbase.

Something like 
ContentElements/MyContentElement/controller.php to overwrite the base logic if needed would also be good.

It would go away from the pure yaml approach, but would make it more adaptable.

If i just didn't find the right thing and it is already possible I'm sorry.

**Comment by nhovratov** [comment]
Hi, so this extension "only" allows you to define your data structure. What you do with it (simple userFunc plugins, Extbase, Content Elements) is up to you.

I am about to write a guide about displaying simple records with plugins in list view / detail view style. But this will be accomplished by already existing functionality.

So in conclusion: As soon as you need a controller for your Content Elements, you are writing a Plugin. And Plugins are simply Content Elements with a Controller attached.

For simple logic, oftentimes a DataProcessor is enough though.

**Comment by dpolakovics** [comment]
Hey,

thanks for the quick answer.
Ok now i understand the Scope better.

Best regards
