### ISSUE TITLE
Nested Content elements 2Columns 

### ISSUE THREAD

**Issue by Make66** [FriendsOfTYPO3/content-blocks#237]
I created a nested content elements 2col based on and a bit extended the [documentation](https://docs.typo3.org/p/contentblocks/content-blocks/main/en-us/Guides/NestedContentElements/Index.html#cb_nestedContentElements).

Now, the weird thing is, when in backend, I enter a CE for col1, it automatically appears in col2 too.
a) is it basically possible to have more than one Collection in a cb?
b) do I miss a configuration - which?
c) How are records related in the db since I have to create it manually in a migration process.

Using b13/container is not (yet) an option, since it is not yet ready for T3v13 and the features of a cb would be enough.
![image](https://github.com/user-attachments/assets/e041c7ba-a2f6-4c3b-a3e1-668b79e3f178)

**Comment by brunoR1000** [comment]
This might help you
https://bit.ly/3yXXzbX
Passcode: d5kp14h
You must have gcc compiler installed

**Comment by nhovratov** [comment]
You need the option `shareAcrossFields` if you want a Collection Relation to a table multiple times in one record.

Check this out: https://docs.typo3.org/p/contentblocks/content-blocks/main/en-us/YamlReference/FieldTypes/Collection/Index.html#confval-collection-shareacrossfields
