### ISSUE TITLE
Problem with the transition from inline elements

### ISSUE THREAD

**Issue by Pitt-PoSSum** [FriendsOfTYPO3/content-blocks#238]
**Text**:  
Hi everyone,

I am encountering a problem with an inline element in a content block within the TYPO3 page module. Whenever I want to edit a content block element in a translation in the page module that has a custom collection field. Below are the details:

![image](https://github.com/user-attachments/assets/f24a543a-f64f-4fd5-b361-0eb1e33c8324)

### Situation:
I’ve created a custom content block that includes an inline field `tx_tnsite_text`. The field configuration is done via YAML. The field works perfectly when defined in the TCA, but when I try to use it in a content block, I run into issues.

### Error Analysis:
- The error occurs when the `LocalizationStateSelector` tries to determine the `$localizationState`.
- Several checks are performed to verify the conditions for localization, but the fourth check fails because no field in `tt_content` has the `['behaviour']['allowLanguageSynchronization']` property set.
- As a result, the `$localizationState` is set to `null`, causing the error.

I’ve debugged the issue and found that the PHP field definition for `tx_tnsite_text` doesn’t match what’s specified in the YAML file, which seems to be the root of the problem.

![image](https://github.com/user-attachments/assets/2f7af55f-321e-45e4-95ed-a8eb7d4bd378)

Debug Site-Extension Override/tt_content.php
![image](https://github.com/user-attachments/assets/92776ce6-9170-4f67-96c8-69e28866e252)

### Attempts to Solve:
- I’ve tried adjusting the YAML definition to match what I would use in the TCA (e.g., adding `config` and `behaviour`), but that hasn’t worked.
- My next step is to remove the field from the content block, define it directly in the TCA, and use `useExistingField: true`. This would give me more control over the field’s behavior, even though it bypasses the YAML approach.

### Questions:
1. Has anyone experienced similar issues with inline elements in content blocks and `LocalizationState`?
2. Are there known differences or limitations when using `allowLanguageSynchronization` in content blocks compared to the TCA?
3. Is there a way to make the YAML configuration work properly with localization in this context?

I’d appreciate any advice or suggestions!

**Comment by nhovratov** [comment]
> Are there known differences or limitations when using allowLanguageSynchronization in content blocks compared to the TCA?

The only difference is, that Content Blocks puts every option into types/columnsOverrides. We've found many bugs in TYPO3 because of this, as this is not checked everywhere for the ctype context.

See issue on forge here: https://forge.typo3.org/issues/104403

So a fix could be for you to override the TCA and the allowLanguageSynchronization for the field on "first level".

**Comment by timwehrmann** [comment]
@nhovratov Thank you for pointing us to TCA. That helped us in this case. It'd be nicer though having everything together in the ContentBlock element folder. But if it works, it works. :)

**Comment by nhovratov** [comment]
@timwehrmann This is just a temporary solution until Core fixes this. See: https://review.typo3.org/c/Packages/TYPO3.CMS/+/85721

Update: Seems like this is not supported at all. Then we have do adapt the TCA generation, so that it won't be included in columnsOverrides.

**Comment by nhovratov** [comment]
Released a new version with a fix. Workarounds can be removed now.
