### ISSUE TITLE
Strengthen make:content-block and provide guidelines

### ISSUE THREAD

**Issue by dkoether** [FriendsOfTYPO3/content-blocks#24]
Hello @nhovratov,

I took my first round with EXT:content-blocks and my first impression is positive!

When creating new content elements with the `make` command I saw that it is possible to create content blocks with whitespaces which also leads to whitespaces in folder names too. On this step I didn't know if it asks for the technical or the content element name for editors.

<img width="308" alt="grafik" src="https://github.com/nhovratov/content-blocks/assets/7765498/daf060d9-eeb1-4089-ab08-7c5fcc2ced73">

For me it was unclear if I should use lowerCamelCase or hyphens to give the content blocks a name. I needed to take a look into the docs and the examples. My lowerCamelCase `pageTeaser` gets processed to lowercase only `pageteaser`.

Maybe you can add some guidelines in the `make` command or also strip of whitespaces to strengthen the create process.

Thanks in advance!
Daniel

**Comment by nhovratov** [comment]
@dkoether Hi Daniel, thank you for your feedback! Yes, we should add validation for the content block name, this is clear. In general the folder name can be different to the content block name in `vendor/content-block-name`. I will add more info in the command itself, so it's easier to use even without the documentation. Thanks!

**Comment by nhovratov** [comment]
The rule is now: vendor and content block name have to be lowercase and separated by a dash. For example: `my-vendor/my-content-block-name`. The command will now validate your input and provide better info.
