### ISSUE TITLE
Dcumentation update for backend view

### ISSUE THREAD

**Issue by Make66** [FriendsOfTYPO3/content-blocks#241]
Please update/extend [documentation here for two issues here](https://docs.typo3.org/p/contentblocks/content-blocks/main/en-us/Guides/NestedContentElements/Index.html#render-nested-content-elements-in-the-backend):
1) Template file name: From 
EXT:my_extension/ContentBlocks/ContentElements/tabs/Source/**BackendPreview**.html
to: EditorPreview.html
2) removed - cannot recreate

P.S. I am accessing a private property with "data._grids.col1" - currently it seems to work
P.P.S Unhiding the Elements make the preview look good.

**Comment by Make66** [comment]
![image](https://github.com/user-attachments/assets/bda4e591-93b4-4075-bb07-681209cf9082)

**Comment by nhovratov** [comment]
Thanks, fixed.
