### ISSUE TITLE
Typo on the 'Page Types' documentation page

### ISSUE THREAD

**Issue by simonmayr** [FriendsOfTYPO3/content-blocks#246]
On the 'Page Types' documentation page (https://docs.typo3.org/p/contentblocks/content-blocks/main/en-us/YamlReference/ContentTypes/PageTypes/Index.html) there is a typo in the file path of the first code block.

![Bildschirmfoto 2024-09-11 um 15 52 17](https://github.com/user-attachments/assets/b05463e8-5e78-4aa8-a140-01068205e60d)

The path lists `PageType` but the folder should be called `PageTypes`.

Very minor typo, but I copied the folder name from the code block example, and it didn't work.

**Comment by nhovratov** [comment]
Thank you for creating this issue! Fixed.
