### ISSUE TITLE
Documentation: Extend TypoScript – dataProcessing example issue

### ISSUE THREAD

**Issue by robinson2** [FriendsOfTYPO3/content-blocks#252]
In the code examples 
https://docs.typo3.org/p/contentblocks/content-blocks/main/en-us/Guides/ExtendContentBlockTypoScript/Index.html#extend-every-content-block
and
https://docs.typo3.org/p/contentblocks/content-blocks/main/en-us/Guides/ExtendContentBlockTypoScript/Index.html#extend-every-content-block
`dataProcessing.10`
is used, but 10 is already used as the [basis](https://docs.typo3.org/p/contentblocks/content-blocks/main/en-us/Guides/ExtendContentBlockTypoScript/Index.html#the-basis-for-each-content-element)
`lib.contentBlock.dataProcessing.10 = content-blocks`
, which is overwritten as a result. This leads to the following error:

> TYPO3\CMS\ContentBlocks\Registry\ContentBlockRegistry::getContentBlockExtPath(): Argument #1 ($name) must be of type string, null given, called in /html/typo3/typo3conf/ext/content_blocks/Classes/ViewHelpers/Asset/CssViewHelper.php on line 135

The examples could be changed to
`dataProcessing.20`
, for example, because that's what works.

**Comment by nhovratov** [comment]
Thanks! Fixed.
