### ISSUE TITLE
IconRoot

### ISSUE THREAD

**Issue by conpassione** [FriendsOfTYPO3/content-blocks#258]
Icon.svg, IconHideInMenu.svg both are working as expectet for PageTypes, but IconRoot.svg doesn't work.
If a PageType used as Root-Page, it shows the standard icon, not the one providet with the PageType.

I am using TYPO3 V13.3.1 and Content-Blocks V0.8.2

**Comment by nhovratov** [comment]
This feature is not yet released. Will be released with 1.0.0. Use the 0.8 documentation please, not main.
