### ISSUE TITLE
Singular for generated directories

### ISSUE THREAD

**Issue by georgringer** [FriendsOfTYPO3/content-blocks#26]
while watching the presentation at mtug I suggest to rename generated directory name `PageTypes` to `PageType` and `ContentElements´ to `ContentElements`

Take a look at other directories `Resource`, `Controller`, `Language`, `Configuration` 

I know `ViewHelpers` is kind of different ^^

**Comment by jonaseberle** [comment]
Thanks Georg for your thought.

I don't have an opinion, just want to mention that there's also `Layouts` `Templates` `Partials`.

**Comment by georgringer** [comment]
yes, it is really inconsistent. I actually don't know whom to ask and a vote is not what we should do (because it is about correct and not who shouts the loudest)

**Comment by nhovratov** [comment]
Yes, I also have no idea what would be best practice.

Examples for singular:
- Controller
- Domain
- Model (Actually most of PHP folders in Classes are singular)
- Language
- Configuration
- Changelog
- DefaultConfigurationDescription.yaml
- additional.php
- system

Examples for plural:
- Resources
- Layouts
- Templates
- Partials
- Classes
- Tests
- ViewHelpers
- Icons
- Overrides
- Backend/Modules.php
- Services.yaml
- JavaScriptModules.php
- ContentSecurityPolicies.php
- assets
- sites
- settings.php

My feeling is that concepts are most often named singular like TCA, TypoScript, PHP classes folders.
On the other side folders and files which hold one or more files / folders / configs of the same type are most often named in plural like FlexForms (one or more XML files), Forms (one or more form yaml files), ContentSecurityPolicies.php (one or more policies).

**Comment by nhovratov** [comment]
I don't think we will change this anymore. Let's keep it as is. My feeling tells me this is right. But I know there are areas, where singular should be used. For example table names, class models and PHP namespaces.
