### ISSUE TITLE
A PageType can have a group?

### ISSUE THREAD

**Issue by subnoodle** [FriendsOfTYPO3/content-blocks#260]
Hoy,

i tried to add "group" in the editorinterface to see if it works, perhaps (not listed in the available options).

```
name: bs/menu-item
typeName: 1728494328
prefixFields: true
prefixType: full
group: Special
```

The result is quite interessting:

- The "add multiple pages"-assistant shows the new Doktype in the group given in the editorinterface-config
- The usual select-box does not consider the group, it's just the default ("Page")

Since the behavior is inconsistent, it's to early to make it in the docs.

Maybe someone can have a look at it?

Thank you for the great work & cheers, Th. 

<img width="641" alt="Bildschirmfoto 2024-10-09 um 19 44 47" src="https://github.com/user-attachments/assets/72efde83-caef-47bf-bbe4-2833bafa4f68">
<img width="656" alt="Bildschirmfoto 2024-10-09 um 19 44 10" src="https://github.com/user-attachments/assets/dd11fde5-dee3-4cb9-9c6a-3ea1d13b23fa">

**Comment by subnoodle** [comment]
Ok, i counter-tested it: I removed the group-option from the editor-interface, emptied all caches and rechecked the result.
It seems that the different page-add-mechanisms work different with custom page-types.

The result stayed the very same.

So, multiple-page-adding and page-type-select-box shows the new page-type still on the same position, but different to each other (the screenshot are the same - with or without group-options.

I change this issue then to a feature request:

Can the group-option in the editor-interface-file be added as well for page-types? Since it's already there for content-elements... would make very sense.

Thank you!
Sam

**Comment by nhovratov** [comment]
@subnoodle Hey, thanks for bringing this up. You are completely right about that `group` should work for the select box of page types. Good news: It works in TYPO3 v13! For Content Elements as well as for Page Types. Unfortunately, for the v12 version this is not possible. Reason: There are two types of groups: The "NewContentElementWizard" and the "record type selector". These are completely independent from each other. In v13 these are aligned, so we were able to define one group for both. I will adjust documentation for v13, to reflect this change.
