### ISSUE TITLE
Typo 13.4 Error after installing Content-blocks

### ISSUE THREAD

**Issue by gmt-it** [FriendsOfTYPO3/content-blocks#261]
Hi.

Got the following error after installing:

Typed property TYPO3\CMS\ContentBlocks\FieldType\AbstractFieldType::$tcaType must not be accessed before initialization.

Error log:

`Tue, 15 Oct 2024 11:40:19 +0000 [CRITICAL] request="748976e618fec" component="TYPO3.CMS.Core.Error.DebugExceptionHandler": Core: Exception handler (WEB: BE): Error, code #0, file /var/www/html/vendor/friendsoftypo3/content-blocks/Classes/FieldType/AbstractFieldType.php, line 43: Typed property TYPO3\CMS\ContentBlocks\FieldType\AbstractFieldType::$tcaType must not be accessed before initialization- Error: Typed property TYPO3\CMS\ContentBlocks\FieldType\AbstractFieldType::$tcaType must not be accessed before initialization, in file /var/www/html/vendor/friendsoftypo3/content-blocks/Classes/FieldType/AbstractFieldType.php:43 - {"mode":"WEB","application_mode":"BE","exception_class":"Error","exception_code":0,"file":"/var/www/html/vendor/friendsoftypo3/content-blocks/Classes/FieldType/AbstractFieldType.php","line":43,"message":"Typed property TYPO3\\CMS\\ContentBlocks\\FieldType\\AbstractFieldType::$tcaType must not be accessed before initialization","request_url":"https://typo133.ddev.site/typo3/module/tools/extensionmanager/List/index?filter=System","exception":"Error: Typed property TYPO3\\CMS\\ContentBlocks\\FieldType\\AbstractFieldType::$tcaType must not be accessed before initialization in /var/www/html/vendor/friendsoftypo3/content-blocks/Classes/FieldType/AbstractFieldType.php:43\nStack trace:\n#0 /var/www/html/vendor/friendsoftypo3/content-blocks/Classes/FieldType/TextFieldType.php(68): TYPO3\\CMS\\ContentBlocks\\FieldType\\AbstractFieldType->getTcaType()\n#1 /var/www/html/vendor/friendsoftypo3/content-blocks/Classes/Definition/TcaFieldDefinition.php(91): TYPO3\\CMS\\ContentBlocks\\FieldType\\TextFieldType->getTca()\n#2 /var/www/html/vendor/friendsoftypo3/content-blocks/Classes/Generator/TcaGenerator.php(492): TYPO3\\CMS\\ContentBlocks\\Definition\\TcaFieldDefinition->getTca()\n#3 /var/www/html/vendor/friendsoftypo3/content-blocks/Classes/Generator/TcaGenerator.php(200): TYPO3\\CMS\\ContentBlocks\\Generator\\TcaGenerator->getColumnTcaForTableWithTypeField(Object(TYPO3\\CMS\\ContentBlocks\\Definition\\TableDefinition), Object(TYPO3\\CMS\\ContentBlocks\\Definition\\TcaFieldDefinition), Array)\n#4 /var/www/html/vendor/friendsoftypo3/content-blocks/Classes/Generator/TcaGenerator.php(176): TYPO3\\CMS\\ContentBlocks\\Generator\\TcaGenerator->generateTableTca(Object(TYPO3\\CMS\\ContentBlocks\\Definition\\TableDefinition), Array)\n#5 /var/www/html/vendor/friendsoftypo3/content-blocks/Classes/Generator/TcaGenerator.php(160): TYPO3\\CMS\\ContentBlocks\\Generator\\TcaGenerator->generate(Array)\n#6 /var/www/html/vendor/friendsoftypo3/content-blocks/Classes/ServiceProvider.php(269): TYPO3\\CMS\\ContentBlocks\\Generator\\TcaGenerator->__invoke(Object(TYPO3\\CMS\\Core\\Configuration\\Event\\BeforeTcaOverridesEvent))\n#7 /var/www/html/vendor/typo3/cms-core/Classes/EventDispatcher/EventDispatcher.php(44): TYPO3\\CMS\\ContentBlocks\\ServiceProvider::TYPO3\\CMS\\ContentBlocks\\{closure}(Object(TYPO3\\CMS\\Core\\Configuration\\Event\\BeforeTcaOverridesEvent))\n#8 /var/www/html/vendor/typo3/cms-core/Classes/Configuration/Tca/TcaFactory.php(187): TYPO3\\CMS\\Core\\EventDispatcher\\EventDispatcher->dispatch(Object(TYPO3\\CMS\\Core\\Configuration\\Event\\BeforeTcaOverridesEvent))\n#9 /var/www/html/vendor/typo3/cms-core/Classes/Configuration/Tca/TcaFactory.php(66): TYPO3\\CMS\\Core\\Configuration\\Tca\\TcaFactory->dispatchBeforeTcaOverridesEvent(Array)\n#10 /var/www/html/vendor/typo3/cms-core/Classes/Configuration/Tca/TcaFactory.php(52): TYPO3\\CMS\\Core\\Configuration\\Tca\\TcaFactory->create()\n#11 /var/www/html/vendor/typo3/cms-core/Classes/Core/Bootstrap.php(152): TYPO3\\CMS\\Core\\Configuration\\Tca\\TcaFactory->get()\n#12 /var/www/html/public/index.php(20): TYPO3\\CMS\\Core\\Core\\Bootstrap::init(Object(Composer\\Autoload\\ClassLoader))\n#13 /var/www/html/public/index.php(21): {closure}()\n#14 /var/www/html/public/typo3/index.php(48): require('/var/www/html/p...')\n#15 {main}"}`

**Comment by nhovratov** [comment]
Could you try clear DI cache? In Install Tool Cache Flush or delete the var/cache/code/di folder.

**Comment by gmt-it** [comment]
Hi.

After deleting the var/cache/code/di folder it works now.

Thank you!

Best regards

Guido
