### ISSUE TITLE
<cb:asset.css - Error after udate to version 1.0.0

### ISSUE THREAD

**Issue by bzimm16** [FriendsOfTYPO3/content-blocks#262]
After having updated form T3 v 13.3.1 to 13.4.0 and content blocks from 0.8 to 1.0.0 i get this error message: 

Fluid parse error in template Default_action_Default_f0d3b1c6f6df3f35, line 1 at character 1. Error: The ViewHelper "<cb:asset.css>" could not be resolved. Based on your spelling, the system would load the class "TYPO3\CMS\ContentBlocks\ViewHelpers\Asset\CssViewHelper", however this class does not exist. (error code 1407060572). Template source chunk: <cb:asset.css identifier="content-block-mssc-mssc/heroimagerelation-be" file="EditorPreview.css"/>

The error persists even after having deleted tc <cb:asset.css ... part in EditorPreview.css

**Comment by nhovratov** [comment]
I wrote this in the release notes for 1.0:

New AssetPathViewHelper

https://github.com/FriendsOfTYPO3/content-blocks/commit/cd4e1d2d66097f06a8a91f1bc4460926fd2d92c6 [!!!][TASK] [Introduce AssetPathViewHelper](https://docs.typo3.org/p/friendsoftypo3/content-blocks/main/en-us/Templating/Index.html#asset-viewhelpers)

We replaced the custom AssetViewHelpers with a new AssetPathViewHelper. Now you can use the Core AssetViewHelpers and only use the custom ViewHelpers to build the path to your asset.

Before

<cb:asset.css identifier="cbAccordionCssBackend" file="EditorPreview.css"/>

After

<f:asset.css identifier="cbAccordionCssBackend" href="{cb:assetPath()}/EditorPreview.css"/>

So, please migrate all occurences and clear the caches. Maybe there are leftovers you've missed somewhere.

**Comment by bzimm16** [comment]
Thanks for your quick answer. I did that already

 

Replacing with 

 

<f:asset.css identifier="xyz" href="{cb:assetPath()}/EditorPreview.css"/>

and even deleting  the tag altogether did not help

I cleard the cache  with:

typo3/sysext/core/bin/typo3 extension:setup --extension=abc

typo3/sysext/core/bin/typo3 cache:flush -g system

but the error persists.

 

 

 

 

Von: Nikita Hovratov ***@***.***> 
Gesendet: Mittwoch, 16. Oktober 2024 10:24
An: FriendsOfTYPO3/content-blocks ***@***.***>
Cc: bzimm16 ***@***.***>; Author ***@***.***>
Betreff: Re: [FriendsOfTYPO3/content-blocks] <cb:asset.css - Error after udate to version 1.0.0 (Issue #262)

 

I wrote this in the release notes for 1.0:

New AssetPathViewHelper

 <https://github.com/FriendsOfTYPO3/content-blocks/commit/cd4e1d2d66097f06a8a91f1bc4460926fd2d92c6> cd4e1d2 [!!!][TASK] Introduce AssetPathViewHelper <https://docs.typo3.org/p/friendsoftypo3/content-blocks/main/en-us/Templating/Index.html#asset-viewhelpers> 

We replaced the custom AssetViewHelpers with a new AssetPathViewHelper. Now you can use the Core AssetViewHelpers and only use the custom ViewHelpers to build the path to your asset.

Before

<cb:asset.css identifier="cbAccordionCssBackend" file="EditorPreview.css"/>

After

<f:asset.css identifier="cbAccordionCssBackend" href="{cb:assetPath()}/EditorPreview.css"/>

So, please migrate all occurences and clear the caches. Maybe there are leftovers you've missed somewhere.

**Comment by nhovratov** [comment]
Well, the error is pretty clear. Please search your whole project for occurences of "cb:asset.css". If clearing cache does not help, there has to be another occurence.

**Comment by bzimm16** [comment]
Sorry, for having bothered you and thank you very much. There was something wrong with the upload to the webserver. The relevant files were not replaced, hence the confusion.

 

 

Von: Nikita Hovratov ***@***.***> 
Gesendet: Mittwoch, 16. Oktober 2024 10:40
An: FriendsOfTYPO3/content-blocks ***@***.***>
Cc: bzimm16 ***@***.***>; Author ***@***.***>
Betreff: Re: [FriendsOfTYPO3/content-blocks] <cb:asset.css - Error after udate to version 1.0.0 (Issue #262)

 

Well, the error is pretty clear. Please search your whole project for occurences of "cb:asset.css". If clearing cache does not help, there has to be another occurence.
