### ISSUE TITLE
[DOCS] Add example to output images in EditorPreview.html

### ISSUE THREAD

**Issue by Alagts** [FriendsOfTYPO3/content-blocks#263]
Currently there is an example missing how to output images with the new content blocks extensions in a backend preview. I recommend to add the following example in Templating/Index.rst. 
 For me this worked out. The field image was used (useExistingField: true). 

```html
<f:image image="{data.image.0}" width="120" maxHeight="100"/>
```

**Comment by nhovratov** [comment]
Would you like to add this example?

Generally, preview and frontend templates work the same, that's why there aren't any specific examples for backend preview. But if this helps, surely we can add it.
