### ISSUE TITLE
Remove duplicate: contentblocks/content-blocks vs friendsoftypo3/content-blocks

### ISSUE THREAD

**Issue by eyemd** [FriendsOfTYPO3/content-blocks#265]
Documentation for content-blocks is also available under the vendor contentblocks. Apparently that should not be used: when doing a `composer require contentblocks/content-blocks`, we get the feedback "Package contentblocks/content-blocks is abandoned, you should avoid using it. Use friendsoftypo3/content-blocks instead".

To avoid confusion https://docs.typo3.org/p/contentblocks/content-blocks/main/en-us should be redirecting to the new source https://docs.typo3.org/p/friendsoftypo3/content-blocks/main/en-us

**Comment by nhovratov** [comment]
Requested this in the documentation team.

**Comment by nhovratov** [comment]
Redirect is merged.
