### ISSUE TITLE
Missing Link to edit in backend-preview for content-elements

### ISSUE THREAD

**Issue by wini2** [FriendsOfTYPO3/content-blocks#268]
With the automatically generated backend-preview.html
_Preview for Content Block: ub-company/cb-card
Header: {data.header}
Image: {data.image}_
the record can be opened to edit.

With customized be-preview the link is missing (s. screenshot) and - beside that - I could not find a way to remove the automatically generated fields.

![content-blocks-be-preview-2024-10-21](https://github.com/user-attachments/assets/45a09504-ab97-43d5-acf8-1f433abfa65c)

Please give me a hint to link e.g. bodytext, if it's not a bug or a missing feature. 

TYPO3 13.4.0/content_blocks 1.0.0

**Comment by nhovratov** [comment]
@wini2 Hi,

1. The auto-generated link with the `header` field can't be removed. It is always there for a "minimum" preview. This comes from TYPO3 Core, so no chance to adjust it easily.
2. If you want to add a link, you can make use of backend ViewHelpers for that. See the example: https://github.com/FriendsOfTYPO3/content-blocks/blob/9d3a271353a5ecf9cbd113224ea78eda6cb03698/Build/content-blocks-examples/ContentBlocks/ContentElements/card_group/templates/backend-preview.html#L16
Do not forget to include the VH namespace in the header. And, in your case change `item` to `data`.

**Comment by wini2** [comment]
@nhovratov 
Thanks a lot! 
2. Works as expected. Because of your hint, I also found it in the manual.
