### ISSUE TITLE
sorting ignored

### ISSUE THREAD

**Issue by glucka** [FriendsOfTYPO3/content-blocks#269]
With this simple config:
  - identifier: image
    useExistingField: true
    type: File
    
f:for each="{data.image}" as="img"

Rendering always in wrong order

**Comment by nhovratov** [comment]
@glucka Which version of Content Blocks do you use?

**Comment by glucka** [comment]
1.0.0

**Comment by nhovratov** [comment]
Ok, thanks. I will check this. If you can provide some more context (screenshots etc., tests) in the meanwhile, this would be great.

**Comment by glucka** [comment]
here with the "media" field the same:
![Screenshot from 2024-10-23 16-57-43](https://github.com/user-attachments/assets/1614009b-6b54-4bc8-a3d3-27052274ac7b)
![Screenshot from 2024-10-23 16-57-58](https://github.com/user-attachments/assets/b00f9856-59a6-46ac-997d-e36d4d83055b)

**Comment by nhovratov** [comment]
@glucka This looks like a Core bug. I will create a forge ticket for that.

**Comment by nhovratov** [comment]
https://forge.typo3.org/issues/105416

**Comment by nhovratov** [comment]
Bug is confirmed and is now reviewed by Core developers. If you can't wait for the next release of v13, you can use composer patch: https://review.typo3.org/c/Packages/TYPO3.CMS/+/86717

**Comment by glucka** [comment]
Thx, i get this error after your patch:
![Screenshot from 2024-10-24 13-19-52](https://github.com/user-attachments/assets/d8bc0bef-41fc-4720-b59d-d676bb6d9b53)
By the way this bug exist in Frontend too.

**Comment by nhovratov** [comment]
Yeah, I saw it too. Needs a bit more tweaking. Thanks for testing, though!

**Comment by nhovratov** [comment]
Patch (see above) for v13 is merged. Will be released with TYPO3 v13.4.1.
