### ISSUE TITLE
Table "tt_content" is defined as language aware but the record misses necessary fields

### ISSUE THREAD

**Issue by kruedger** [FriendsOfTYPO3/content-blocks#272]
If you use the new pageview with the DataProcessor page-content, the following TYPO3 error occurs:
Table “tt_content” is defined as language aware but the record misses necessary fields: Record property “sys_language_uid” is not available.
Here is a comparison of the data from the DataProcessor when I use the old dynamicContent method and the new one via the DataProcessor
![image](https://github.com/user-attachments/assets/4129b1c7-fa12-4ca1-9535-3ae46bdf5a84)
![image](https://github.com/user-attachments/assets/6fc8b8dc-9042-4dcf-9fbf-db2368c8ae4d)

**Comment by nhovratov** [comment]
@kruedger You need to provide the raw record for the rendering:

For example:

```
<main>
    <f:for each="{myContent.main.records}" as="record">
        <f:cObject typoscriptObjectPath="{record.mainType}" table="{record.mainType}" data="{record.rawRecord}"/>
    </f:for>
</main>
```

See also: https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/13.2/Feature-103894-AdditionalPropertiesForColumnsInPageLayouts.html#feature-103894-additional-properties-for-columns-in-page-layouts
