### ISSUE TITLE
Exclude nested Content Elements in PageContentFetchingProcessor

### ISSUE THREAD

**Issue by nhovratov** [FriendsOfTYPO3/content-blocks#273]
Core needs to provide an event listener for this.

**Comment by kraemer-igroup** [comment]
Could this please be documented somewhere? I was very irritated, that the suggest way of the "Site package tutorial" did not work properly with nested content blocks (https://docs.typo3.org/permalink/t3sitepackage:page-content-data-processor).

I know this part, but it was not obvious to me this also affects page-content (or how to solve it): 
https://docs.typo3.org/permalink/friendsoftypo3-content-blocks:cb-nesting-prevent-output-fe

(edited: fixed permalink, info about "Nested content" moved from "Guides" to "API")

**Comment by nhovratov** [comment]
I will add a warning as long as this is not possible.

**Comment by nhovratov** [comment]
Forge issue: https://forge.typo3.org/issues/105638
