### ISSUE TITLE
Table "tt_content" is defined as language aware but the record misses necessary fields

### ISSUE THREAD

**Issue by MatthiasRixen** [FriendsOfTYPO3/content-blocks#274]
Hi,

if i try to fetch Content in my template the new way like this: 

`<f:for each="{content.main.records}" as="record"><f:cObject typoscriptObjectPath="tt_content.{record.CType}" data="{record}" table="tt_content"/></f:for>`

typoscript is:

`page.10.dataProcessing.10 = page-content`

in the Frontend I get the following Exception:

> Table "tt_content" is defined as language aware but the record misses necessary fields: Record property "sys_language_uid" is not available.

If i try it the "old fashioned" way with dynamicContent Helper; 

`<f:cObject typoscriptObjectPath="lib.dynamicContent" data="{colPos: '0'}"/>`

everythings works fine!

Fresh TYPO3 13 with content_blocks 1.0.3. Sitepackage generated via Sitepackagebuilder.

Can anybody help?

Thanks!

**Comment by nhovratov** [comment]
See: https://github.com/FriendsOfTYPO3/content-blocks/issues/272

**Comment by MatthiasRixen** [comment]
Helped! Thx!
