### ISSUE TITLE
Create custom html templates for new content blocks

### ISSUE THREAD

**Issue by PKuhlmay** [FriendsOfTYPO3/content-blocks#279]
It would be nice if I can create my own templates for all the new content block which I create. At the moment they are generated with `contentblocks/content-blocks/Classes/Generator/HtmlTemplateCodeGenerator.php:generateEditorPreviewTemplate` and `generateFrontendTemplate`.

**Comment by nhovratov** [comment]
Idea for a concept:

There could be a folder, with two fluid templates:

- content-blocks-default-templates
  - backend-preview.html
  - frontend.html

If you then run:

`make:content-block --template-path="./content-blocks-templates"`

then your standard templates will be used instead.
This could further be simplified by a `content-blocks.yaml` config file on root level, where you can define default values:

```
template-path: content-blocks-templates
vendor: z3
extension: my_sitepackage
```

A default vendor and host extension could be a very nice feature to top it.

**Comment by krausandre** [comment]
Questions in my head:

- Where to dump the default template? (best practice documentation)
- What is the use case for a default frontend template?
- Do we break the concept by giving an API to add external dependencies?
- Where to dump the content-blocks-config.yaml? Maybe in Configuration directory?
- How do we handle, if more than one extension brings a content-blocks-configuration.yaml? (think of the default extension config part)

I love the Idea to have a default vendor and default extension given. But there could be conflicts I guess. It also could pay to the goal, to reduce TypoScript for partials and layout paths. But giving API to external dependencies is still a big question I think.

**Comment by nhovratov** [comment]
@krausandre I already implemented it. See here: https://github.com/FriendsOfTYPO3/content-blocks/pull/304
Most of your questions should be answered by this.

This is not an external dependency. It's a project-specific config / default when you use the make command. In fact, we could extract the make command, together with this feature into a separate extension "make ?".
