### ISSUE TITLE
Provide yaml validator for IDEs

### ISSUE THREAD

**Issue by georgringer** [FriendsOfTYPO3/content-blocks#28]
see https://github.com/georgringer/typo3-json-schemas and the final PR https://github.com/SchemaStore/schemastore/issues/2524

I suggest not add a PR once all configurations are final and use a custom import of the schema until then

**Comment by jonaseberle** [comment]
We might (maybe) want to use that for generation of the properties in the GUI as well. 
Work has started here: https://github.com/krausandre/content-blocks-gui/blob/main/packages/content_blocks_gui/Build/JsonSchema/contentblocks-content-element.json

**Comment by nhovratov** [comment]
Created new repository for this now:  https://github.com/nhovratov/content-blocks-json-schema
This is almost complete. Only a few Field Types are missing.
