### ISSUE TITLE
AutomaticLanguageKeysRegistry::getByContentBlock(): Return value must be of type array, null returned

### ISSUE THREAD

**Issue by linawolf** [FriendsOfTYPO3/content-blocks#283]
I am trying to migrate my first content element from Mask to Content blocks following this https://docs.typo3.org/p/friendsoftypo3/content-blocks/main/en-us/Migrations/Mask/Index.html#mask

When calling 

ddev typo3 content-blocks:language:generate tx-mask/cardbox

Uncaught TYPO3 Exception TYPO3\CMS\ContentBlocks\Registry\AutomaticLanguageKeysRegistry::getByContentBlock(): Return value must be of type array, null returned
thrown in file /var/www/html/vendor/friendsoftypo3/content-blocks/Classes/Registry/AutomaticLanguageKeysRegistry.php
in line 49

**Comment by nhovratov** [comment]
@linawolf Which version are you on?

**Comment by linawolf** [comment]
TYPO3 13.4.0,  mask/mask dev-main, friendsoftypo3/content-blocks (1.0.3)

**Comment by linawolf** [comment]
After uninstalling mask it seems to work

**Comment by nhovratov** [comment]
This is a bug. The fix is to clear the system caches before running the command. Uninstalling Mask probably did this for you.

TODO: Avoid cached language keys in command.
