### ISSUE TITLE
[DOCS] superflous example inside Select field -> maxitems for selectsingle

### ISSUE THREAD

**Issue by PKuhlmay** [FriendsOfTYPO3/content-blocks#289]
In the documentation https://docs.typo3.org/p/friendsoftypo3/content-blocks/main/en-us/YamlReference/FieldTypes/Select/Index.html#advanced-use-case there is `maxitems: 3 `defined, but also `rendertype: selectSingle`.
Isn't this superflous as maxitems has no effect because you can only select one item because of the rendertype? This could confuse users.

**Comment by PKuhlmay** [comment]
And also the settings
```
    minitems: 1
    required: true
```
doesn't seem to have any effect? When I set this and I save the element, the first value is set and I dont get any warning that this field is required.

**Comment by nhovratov** [comment]
maxitems doesn't make sense for renderType: selectSingle
