### ISSUE TITLE
Examples inside Docs for kickstart command still has "make:" instead of "content-blocks:"

### ISSUE THREAD

**Issue by PKuhlmay** [FriendsOfTYPO3/content-blocks#299]
Inside the documentation https://docs.typo3.org/p/friendsoftypo3/content-blocks/main/en-us/Commands/Make/Index.html#kickstart-command the examples are still with `make:` instead of `content-blocks:`

![CleanShot 2024-11-19 at 18 51 13](https://github.com/user-attachments/assets/fc9b498d-4d02-47d1-b707-cd816a027d35)

Should be:

![CleanShot 2024-11-19 at 18 51 54](https://github.com/user-attachments/assets/2621457f-c4d9-4025-8cfb-ec1125d90712)

**Comment by nhovratov** [comment]
@PKuhlmay That's ok. make is only an alias, but I find it better to write.

**Comment by nhovratov** [comment]
@PKuhlmay I hope its ok if I close this. So, the reason behind `make` is a possible future integration into the b13/make extension. So if people get used to this command, it will be easier for them to switch.
