### ISSUE TITLE
images in collection

### ISSUE THREAD

**Issue by wini2** [FriendsOfTYPO3/content-blocks#328]
I try to generate a collection with images

    identifier: eine_karte_fuer_sammlung
    type: Collection
    labelField: header
    fields:
      - 
        identifier: header
        type: Text
        useExistingField: true
        
      - 
        identifier: subheader
        type: Text
        useExistingField: true
      
      - 
        identifier: testimonial_image
        type: File
        maxitems: 2 
        extendedPalette: true    
        
      - 
        identifier: testimonial_teaser
        type: Textarea
        enableRichtext: true
        richtextConfiguration: full 

      - 
        identifier: testimonial_text
        type: Textarea
        enableRichtext: true
        richtextConfiguration: full         
 
 

For backend-preview and frontend
			<f:for each="{data.eine_karte_fuer_sammlung}" as="item">
				<f:transform.html>{item.testimonial_teaser}</f:transform.html>
				<f:transform.html>{item.testimonial_text}</f:transform.html>
			</f:for>

works as expected. But whatever I tried, for images error-messages show up or the code is ignoreded, e.g.

<f:for each="{data.eine_karte_fuer_sammlung}" as="item">
	<f:media file="{item.testimonial_image}" />
</f:for>

Is this a bug, missing feature or my fault? In a non-collection-cases (more simple content-block-examples) it works fine.

--
content-blocks 1.1
TYPO3 v13LTS

**Comment by nhovratov** [comment]
The image field `{item.testimonial_image}` is an array. The question is: Should it be possible to select more than 1 image? (Because you've set `maxitems` to 2. If yes, you need to do a loop:

```
<f:for each="{data.eine_karte_fuer_sammlung}" as="item">
    <f:for each="{item.testimonial_image}" as="image">
        <f:media file="image" />
     </f:for>
</f:for>
```

Otherwise you can define the cardinality with `relationship`. This will automatically set `maxitems` to one and you don't need to access it in a loop like I showed above.

```
    identifier: testimonial_image
    type: File
    relationship: manyToOne 
    extendedPalette: true    
```

**Comment by wini2** [comment]
Thanks for your answer.

I need al least two images, one for the company-logo, one for the person, maybe more in other use-cases. So I think its an general problem to me. 

Your suggestion with for-each works - don't know, what my fault was (sorry for annoying you).

Is there no easy way to make use of the TYPO3 gallery-processor with content-blocks?

**Comment by nhovratov** [comment]
> Is there no easy way to make use of the TYPO3 gallery-processor with content-blocks?

Simply use TypoScript, like you would do for any other Content Element. See here for more info: https://docs.typo3.org/p/friendsoftypo3/content-blocks/main/en-us/Guides/ExtendContentBlockTypoScript/Index.html

**Comment by wini2** [comment]
Hope untill I'm more familiar with your great extension, the simple use of gallery processor is implemented ;-)

Many thanks for your support
