### ISSUE TITLE
Custom ResourceViewHelper

### ISSUE THREAD

**Issue by greenfieldr** [FriendsOfTYPO3/content-blocks#38]
This might be a not necessary, nice to have feature or maybe there's another solution for this I didn't realized yet. If so, please let me know. ;) 
Regardless of this it would just add a small portion of convenience imo. 

To the point: beside JS and CSS files sometimes we might want to access other Assets like e.g. icons within our views. 

My idea was, even if the path to the public assets is not cryptic and predictable, maybe it could be a nice addition to allow easy access to this path. I know, it's just the combination of two static strings (_assets and cb) and the name of the content block including it's vendor, I thought it might be nice to not combine this parts manually every time. 

Not sure if a custom uri.resource-ViewHelper should be the solution or if a simple method inside the ContentBlockData object returning the path as a string would be enough. 

The second would be very easy to implement as the name of the block including the vendor is part of the object anyway. 

If you think this mini feature is worth it to be implemented, please let me know and I could prepare a PR for it.

**Comment by nhovratov** [comment]
I recently changed the symlinks to align with the Core. So they are now als md5 hashed and not inside a separate cb folder. Just as a side note.

For static assets: Yes, I have this on my radar. We need a custom ImageViewHelper (and possibly also uri.image and uri.resource). I have already created a Core patch, to extract image processing logic, so I can use it in a custom ViewHelper. This will take a while until it's merged. For the meantime you can simply use the normal ViewHelpers and resources from Resources/Public. Later this can be refactored and moved to the Content Block directly.
