### ISSUE TITLE
Localizable items for select, check and radio

### ISSUE THREAD

**Issue by greenfieldr** [FriendsOfTYPO3/content-blocks#39]
As every Content Block comes with its own locallang-file, maybe it would be nice to provide a shorter syntax to access language keys within the XLIFF-files of the own content block? 

Would be TBD how this could look like without building a maybe confusing, isolated solution which only works for Content Blocks but anywhere else. Especially thinking about TYPO3 newcomers here. 

If you think it's nevertheless worth it to think further about implement a solution for this, don't hesitate to let me know. :-)

**Comment by nhovratov** [comment]
Do you have an example, where you use labels from the local lang file in EditorInterface.yaml? Most of the labels should be covered by the automatic naming schema. Only if you need labels outside of Content Blocks you would have to include the full LLL-syntax.

**Comment by greenfieldr** [comment]
Currently used it to get translatable labels for select options as the documentation example uses hardcoded labels and mentions that LLL references are possible. 
If there's already an easier way to achieve this, please let me know. If so, I can also provide some docs for it if you like.

**Comment by nhovratov** [comment]
Hm, no I think for select items there is no easier way right now. @krausandre Do you know if there was a plan to provide automatic language keys for select items?

**Comment by greenfieldr** [comment]
As @nhovratov mentioned in the last comment, of course automatic language keys based on the value and make the label property optional would be a convenient solution as well and would also eliminate possible confusion with a separate short-hand syntax which only works within content blocks. 

As mentioned before: Don't hesitate to send me a message and let me know if I can help implementing such a feature.

**Comment by krausandre** [comment]
@nikonierer @nhovratov Due to our existing convention, I think about something like `<identifier>.option.0.label` so you "can read" it is a label to an option and the index. What do you think about that?
In fact, we currently have not planned to provide this, but for better UX we should think about it and if there is a way to support this.

**Comment by nhovratov** [comment]
This syntax has the downside that if you change the order of items, your labels will be messed up. Maybe we should do it like `<identifier>.option.<value>.label` ?

**Comment by krausandre** [comment]
I don't know ad hoc if this is possible, but if so, sounds great.

**Comment by nhovratov** [comment]
Implemented in https://github.com/nhovratov/content-blocks/commit/a440a845f23eb552bc6c4fa27918f554d74b7966
