### ISSUE TITLE
dropdown for color is always the default value

### ISSUE THREAD

**Issue by PKuhlmay** [FriendsOfTYPO3/content-blocks#4]
I created a contend block which has the following settings:

```
name: treupo/color
group: contentblocks
prefixFields: false
fields:
  - identifier: color
    type: Color
  - identifier: colortwo
    type: Color
    autocomplete: true
    default: '#0000FF'
    valuePicker:
      items:
        [
          [ 'Red', '#FF0000' ],
          [ 'Green', '#008000' ],
          [ 'Blue', '#0000FF' ],
        ]
```

When I edit the element in the backend and select one of the colors and then open the dropdown again, the selected color is always the one without a value:
<img width="518" alt="Bildschirmfoto 2023-06-27 um 21 12 35" src="https://github.com/nhovratov/content-blocks/assets/107543296/65a6aada-1089-4d5e-bce8-4894dd0fb63c">

I expected, that my select color will be the selected one inside the dropdown.

**Comment by PKuhlmay** [comment]
The same for the link, where I can have a dropdown.

![Bildschirmfoto 2023-06-28 um 12 52 35](https://github.com/nhovratov/content-blocks/assets/107543296/cddce42a-87d1-4a5a-96be-5511c1815c3b)

**Comment by nhovratov** [comment]
@PKuhlmay I think this is how it us supposed to work. It is just a simple value picker and does not know what is inside your Input field.
