### ISSUE TITLE
Content Block Assets must not be published on application runtime

### ISSUE THREAD

**Issue by helhum** [FriendsOfTYPO3/content-blocks#40]
Instead these should be published on Composer build time, just like TYPO3 solves this.

Additionally, for Windows support, on Windows junctions should be created instead of Symlinks.

**Comment by nhovratov** [comment]
@helhum Are you able to help us out here? Simply some advise would be sufficient if you are not able help hands on.

**Comment by nhovratov** [comment]
@helhum I believe this is not so dramatic anymore as it used to be. The symlinks are created as soon as TYPO3 boots e.g. with `typo3 cache:warmup`. So in deployment processes this is not created from a user clicking on an uncached page. I hope this will suffice for the Core. At least there were no issues for half a year and there are many people using it in production.

Support for windows junctions is still an issue, though.

**Comment by helhum** [comment]
The thing here is: people will use it on Windows, as bug reports for asset publishing of the core has shown.

I suggested to create junctions during composer build runs, as there is API for that already. Writing that code isn't straightforward though, as TYPO3 does not expose which composer based packages are extensions in that build run, so contentblocks would need to duplicate a lot of code.

So either TYPO3 core must provide API, or provide a way to have multiple/ other public folders, or ContentBlocks would need to put public assets into the Resources/Public folder somehow, e.g. by linking (or maybe even copying on runtime) to `Resources/Public/ContentBlock/<content-block-name>/Assets/`

**Comment by nhovratov** [comment]
Thanks Helmut, we adapted your suggestion with symlinking into the Resources/Public folder. Tests already work. We will do some more testing and maybe check if junctions are easy to implement (Symfony FileSystem doesn't seem to support it).

**Comment by helhum** [comment]
Thanks!
