### ISSUE TITLE
[QUESTION / ENHANCEMENT] XLIFF format version 

### ISSUE THREAD

**Issue by secured** [FriendsOfTYPO3/content-blocks#42]
TYPO3 Core seems to use xliff version 1.2
(https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/ApiOverview/Localization/XliffFormat.html).

The generated Labels.xlf is using version 1.0.

Is there a reason why this version is used?
And would it be an advantage to change to the same standard as the TYPO3 core?

**Comment by nhovratov** [comment]
Ah, good catch! We will update to xliff 1.2
