### ISSUE TITLE
CLI command should be content-block:make and not make:content-block

### ISSUE THREAD

**Issue by PKuhlmay** [FriendsOfTYPO3/content-blocks#43]
Hi at the moment, the CLI for creating a content block is `make:content-block`. When looking at the other CLI commands, everyone starts with the extension (or the scope for which it is written) and then the specific command. Like `install:setup`, _database:updateschema_, _scheduler:run_. 
So i suggest renaming the CLI command, so the scope is named first (content-block or content-blocks) and then the specific command (make). So when you have to add some more commands, like update, remove or something else, it would be `content-block:update`, `content-block:remove`. So all the commands for CB are listed in the same area and not under _update_, _remove_ or _make_.
<img width="207" alt="Bildschirmfoto 2023-11-10 um 21 02 49" src="https://github.com/nhovratov/content-blocks/assets/107543296/f4834cf4-6e01-4f23-b0f5-6f47f3fbf450">

**Comment by secured** [comment]
I think that's a good idea. Otherwise it could confuse people who use the extension "b13/make" which also uses this namespace.

(https://github.com/b13/make)

**Comment by nhovratov** [comment]
This was actually the idea to align it with b13/make

**Comment by secured** [comment]
Should we let the community or the development team vote on this?

Just a few thoughts:
- What happens when the Make extension is deprecated?
- Update the README to clarify the intention to align with the Make extension?
- What happens if more commands are added that are exclusive to the content blocks?

**Comment by PKuhlmay** [comment]
My thoughts:
The commands for b13/make all start with "make", **so the extension name comes at first**, and then "what you can make". e.g. make:backendcontroller creates a backend controller. So all the commands for the make-extension are under "make".

<img width="781" alt="Bildschirmfoto 2023-11-15 um 08 18 05" src="https://github.com/nhovratov/content-blocks/assets/107543296/deb7eb25-5211-4846-b19e-a478ab7c9e97">

In this screenshot there is the command make:content-block which at first assume that this is part of the make extension, because it is under "make".

It would be more clear, if the make:content_block command is under a seperate section, like "content_block".

**Comment by nhovratov** [comment]
I changed `make:content-blocks` to an alias. Now it won't be listed anymore in the `make` namespace, but you still can use it. The base command is now `content-blocks:create`. I think this is a fine solution.
