### ISSUE TITLE
[DISCUSSION] Should the SEO tab be visible by default for new page types?

### ISSUE THREAD

**Issue by PKuhlmay** [FriendsOfTYPO3/content-blocks#46]
Hi I created a new page-type and at first I was wondering where the SEO-Tab is. 
I could add it very fast with the basic "TYPO3/Seo" (btw this basic is not documented yet, I will creat another issue)

But .....

we need to discuss whether we should add the SEO tab by default or not. There are some other tabs which are (in my opinion) much less important than the SEO tab (like Notes-Tab).

I understand, that when somebody creates a new page type, he might not want to have all the tabs (because maybe that is why he wanted to create his own page type). But in my case I only wanted to have some more options for a page, like background_color. In my case I added the SEO tab with the basics so the user can change these fields.

I think we should add either all tabs, which are already in the "standard" page (doktype 1?) or none of them (and then the integrator/developer must add them with the basics). For me it didn't make any sense as I realized that the SEO Tab is missing (which is important for pages for SEO) and the Notes-Tab is there (which I have never used before).

**Comment by nhovratov** [comment]
See https://github.com/nhovratov/content-blocks/issues/47
