### ISSUE TITLE
Path for Partials is wrong

### ISSUE THREAD

**Issue by PKuhlmay** [FriendsOfTYPO3/content-blocks#50]
Hi,

I tried to use a partial inside my html template. In the frontend I got the message:

**The Fluid template files "SITEPACKAGE/ContentBlocks/ContentElements/headline/Source/PartialsHeader/Header.html", "SITEPACKAGE/ContentBlocks/ContentElements/headline/Source/PartialsHeader/Header" could not be loaded.**

There is an `/` missing between Partials and the first "Header" -> `Source/PartialsHeader/Header`
When I add the Folder `Source/Partials` I don't get this issue any more. 
It only occurs when the Partials Folder is missing.

The message itself is correct, only the missing `/` is not correct.

**Comment by nhovratov** [comment]
This looks like a mistake from the fluid error message not adding the slash. Well, adding slashes to the path does no harm for Content Blocks, so I will do it.
