### ISSUE TITLE
Allow additional Partial/LayoutRootPaths for EditorPreview view

### ISSUE THREAD

**Issue by kuepper-faktor-e** [FriendsOfTYPO3/content-blocks#57]
Knowing that the independence of content blocks is basically one of the big factors for the use of this extension, in my view there are always cases where content block independent partials make sense. 

For example, we use standardized palettes and partials for the frontend rendering of project-specific content elements. What is missing here is the simple option of creating reusable partials for the backend preview. 

One example from my current projects would be a partial for the preview of the header palette, as all elements share the same palette and a preview of the headline, position and layout desired. 

Since such cases occur again and again, especially with project-specific elements, we would prefer to avoid redundancy in the EditorPreview templates here.

I'm aware that these templates are rendered in the BackendContext and that the TypoScript here is dependent on the SysTemplate in the corresponding part of the page tree. Nevertheless, I think it would be good to find a solution for this. 

The aspect of a "basic extension" is also certainly exciting and would certainly offer even more possibilities, which we would probably also use. 
But even if we take this out of the equation, it might also be a suitable solution to be able to define partials within the ContentBlocks directory independent from a specific content block, similar to the palettes/basics feature.

Let me know what you think and feel free to give me a ping if you wanna discuss this further.

**Comment by jonaseberle** [comment]
Suggestion:

TsConfig:
```
mod.web_layout.content_blocks {
  view {
    partialRootPaths {
    }
    layoutRootPaths {
    }
  }
}
```
