### ISSUE TITLE
Conditionally show backend fields

### ISSUE THREAD

**Issue by mreiners1** [FriendsOfTYPO3/content-blocks#58]
Is it possible to show a certain editing field based on another fields value? 

Tried using displayCond
  - identifier: radio
    type: Radio
    default: 0
    items:
    - label: Option 1
      value: 0
    - label: Option2 2
      value: 1
  - identifier: testtext
    type: Text
    displayCond: 'FIELD:radio:=:1'

got exception: "Multiple conditions must have boolean operator "OR" or "AND", "" given."

**Comment by nhovratov** [comment]
Hey, yes this is possible. You seem to have a syntax error in `displayCond` so TYPO3 throws an exception.

**Comment by mreiners1** [comment]
thanks a lot for your quick reply! Would you mind to show me a quick example, couldn't find any in the documentation

**Comment by nhovratov** [comment]
This option originates from TCA: https://docs.typo3.org/m/typo3/reference-tca/main/en-us/Columns/Properties/DisplayCond.html
`FIELD:identifier:=:1` should work. However, if you have prefixes enabled, you must add them too. So for example `FIELD:myvendor_myname_identifier:=:1`

**Comment by bp-jweber** [comment]
Got the same problem. The regular displayCond-syntax from TCA does not work. An error is thrown in typo3/cms-backend/Classes/Form/FormDataProvider/EvaluateDisplayConditions.php (Multiple conditions must have boolean operator "OR" or "AND", "" given.).

**Comment by garvinhicking** [comment]
Could it be that this :=: syntax creates YAML parsing issues and it's not passed on properly to the TCA?

**Comment by nhovratov** [comment]
This could be possible @garvinhicking Will have a look.

**Comment by nhovratov** [comment]
Oh, this is because it is possible to use a string and an array. But Content Blocks only supports array syntax.

@bp-jweber 
@mreiners1 
I will fix this. For now, you can use the array syntax:

```
    displayCond:
      AND:
        - 'FIELD:full_identifier:=:1'
```
