### ISSUE TITLE
File metadata not available

### ISSUE THREAD

**Issue by Hobokens** [FriendsOfTYPO3/content-blocks#65]
When I debug the file metadata, I only get the title, alternative title and description when I enter these in the content element to overwrite the 'original strings'.
The 'original' file metadata are not displayed. This also applies to the fields that are added by the `filemetadata `extension.

**Comment by jonaseberle** [comment]
@Hobokens original (`sys_file_metadata`) vs. overwritten (`sys_file_reference`) file properties work as expected for me.
I tried an image with `f:image image="{file}"` and also `{file.title}`, `{file.alternative}`.

You might have to use the `properties()` [proxy for the additional EXT:cms-filemetadata fields](https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/ApiOverview/Fal/UsingFal/Frontend.html).

**Comment by Hobokens** [comment]
@jonaseberle Thanks, you are right. I played around with the [slider example for content blocks](https://github.com/TYPO3-Initiatives/content-blocks-examples/tree/main/ContentBlocks/ContentElements/imageslider) and get the properties with i.e. `{asset.properties.creator}`
