### ISSUE TITLE
Missing TCA type uuid

### ISSUE THREAD

**Issue by nhovratov** [FriendsOfTYPO3/content-blocks#75]
https://docs.typo3.org/m/typo3/reference-tca/main/en-us/ColumnsConfig/Type/Uuid/Index.html

**Comment by nhovratov** [comment]
If someone wants to contribute, this should be fairly easy. Just add another FieldConfiguration class + Tests + Documentation.

**Comment by PKuhlmay** [comment]
I'll try this.
