### ISSUE TITLE
The exclamation mark for mandatory fields seems to be slightly displaced

### ISSUE THREAD

**Issue by PKuhlmay** [FriendsOfTYPO3/content-blocks#8]
See Screenshot:
![Bildschirmfoto 2023-06-28 um 12 59 04](https://github.com/nhovratov/content-blocks/assets/107543296/9350f696-e8eb-48e3-8272-b4bd084b79e0)

I think the exclamation mark for the required field "url" needs some more space to the right and maybe a little bit more up.
See for example the space inside the tab "General"

**Comment by nhovratov** [comment]
Yes, this seems to be a Core Backend UX issue. Do you mind creating a ticket in forge instead?

**Comment by PKuhlmay** [comment]
This works in TYPO3 12.4.2 but not in 12.4.3 (currently in dev, not released yet). This might be related to the core bug https://forge.typo3.org/issues/101221 so I close this for now.
