### ISSUE TITLE
Shared Partial - not working as described in docs?

### ISSUE THREAD

**Issue by secured** [FriendsOfTYPO3/content-blocks#86]
I have tried to use the "shared partials" as described in the [documentation](https://docs.typo3.org/p/contentblocks/content-blocks/main/en-us/Guides/SharedPartials/Index.html). relevant [issue](https://github.com/nhovratov/content-blocks/issues/55)

lib.contentblock gets updated:
![Bildschirmfoto 2024-01-16 um 12 10 23](https://github.com/nhovratov/content-blocks/assets/2052936/f58f0f55-f4b9-41b3-bb33-e1402f7444ad) 

but the element does not:
![Bildschirmfoto 2024-01-16 um 12 10 40](https://github.com/nhovratov/content-blocks/assets/2052936/065a9043-3640-450c-80e9-eb2f900c3784)

Have I missed something here?

**Comment by nhovratov** [comment]
Sorry, I don't understand what you are trying to show me. The first picture shows that you have overridden partialRootPaths gloabally for all Content Blocks. So You can use it now everywhere. The second picture shows `templateRootPaths`, which is the default for Content Blocks. I can't see what's inside `partialRootPaths` there.

**Comment by secured** [comment]
ah sorry. that was my mistake. i had opened the wrong branch. the global change "partialRootPaths" is not passed on to the content element.

![Bildschirmfoto 2024-01-16 um 14 21 53](https://github.com/nhovratov/content-blocks/assets/2052936/13c29241-5864-4595-8b02-98ea626c67f8)

**Comment by nhovratov** [comment]
I don't think the debug tool will show that. You can see this is a reference `=<` to `lib.contentBlock`. So everything which is shown will additionally override these options.

**Comment by nhovratov** [comment]
@secured Please re-open the issue, if this does not work for you. I think you just mis-interpreted the debug output.

**Comment by secured** [comment]
Everything now works as desired. I was just stupid. I had selected the wrong element in the frontend and then wondered why the changes didn't work. 😨 

Keep up the good work!

**Comment by wtdesign** [comment]
I have the same Problem. But only in Backend.

Here is the error-message:
![image](https://github.com/nhovratov/content-blocks/assets/45423295/013a43f5-3220-4d77-a927-0459d33264d1)

That is my typoscript:
```
lib.contentBlock {
	layoutRootPaths {
		10 < lib.contentElement.layoutRootPaths.0
	}
	partialRootPaths {
		10 < lib.contentElement.partialRootPaths.0
		100 = EXT:wtBasics/Resources/Private/Partials/ContentElements/
	}
}
```
it works only in Frontend.
![image](https://github.com/nhovratov/content-blocks/assets/45423295/9c6d4373-3798-4871-9f19-ae7b59377e25)

My own content_blocks do not show the above path
![image](https://github.com/nhovratov/content-blocks/assets/45423295/42696681-b49c-4579-9c3e-02736f503b93)

When I write the following typoscript, the same error is still thrown
```
tt_content.wecotec_slidermittext {
	partialRootPaths {
		100 = EXT:wtBasics/Resources/Private/Partials/ContentElements/
	}
}
```
Isn't it possible to use Partials for the backend?

How I can solve the problem?
Kind regards

**Comment by nhovratov** [comment]
@wtdesign 
Frontend and backend have completely different rendering mechanisms. We already have an issue for backend partials here:
https://github.com/nhovratov/content-blocks/issues/57

**Comment by wtdesign** [comment]
@nhovratov Okay, thank you!
