### ISSUE TITLE
Content Block Page Types should provide title in processed array

### ISSUE THREAD

**Issue by nhovratov** [FriendsOfTYPO3/content-blocks#88]
There are some fields which are often used for pages in the frontend and should therefore be easily accessed:
- title
- slug
- nav_title
- abstract (?)
- description
- keywords

**Comment by PKuhlmay** [comment]
In my case, I also need **abstract** and **description**, because they are maintained inside the page-settings and I want to output them in the frontend. I use my own pagetype.

**Comment by nhovratov** [comment]
Okay, I will consider these as well.

**Comment by nhovratov** [comment]
@PKuhlmay May I ask you what you are using `abstract` for? This field is not included by Content Blocks per default, so you have to define it in the Yaml definition.

**Comment by nhovratov** [comment]
Added only title, slug and nav_title for now. The description field is special as it is moved by EXT:seo into another tab. So this can't be defined by Content Blocks. At least not in v12.
