### ISSUE TITLE
Add hint to Readme regarding typo3temp and the indexing in IDEs like PhpStorm

### ISSUE THREAD

**Issue by peterkraume** [FriendsOfTYPO3/content-blocks#89]
The hint in the README.md I introduced in #81 is also included in the [TYPO3 Contribution Guidelines](https://docs.typo3.org/m/typo3/guide-contributionworkflow/main/en-us/Testing/Index.html#additional-setup).

For me that hint is crucial because PhpStorm becomes ununsable when I run functional or unit tests because the IDE tries to index all the thousands of additional files which are generated with each test run. And with each further run the situation becomes worse.

Maybe we can get deeper knowledge from e.g. Stefan Bürk or others which know the TYPO3 testing framework well.

**Comment by nhovratov** [comment]
This is weird, because Unit/Functional Tests don't generate any files as far as I know. This is only done for acceptance tests.

**Comment by peterkraume** [comment]
This is how the directory looks like on my machine:
![Screenshot_2024-01-18_09 47 16](https://github.com/nhovratov/content-blocks/assets/4234704/8dce5105-53d2-4ce8-ab6a-167ba15466c8)

**Comment by nhovratov** [comment]
Ah right, functionals do create these as well. Do you want to create a new PR for that?
