### ISSUE TITLE
[FEATURE] Localization for Basics

### ISSUE THREAD

**Issue by thommyhh** [FriendsOfTYPO3/content-blocks#91]
It would be a nice addition to have language files for the Basics like for the content blocks, so we don't need to define language paths manually for the Basics.

The file could be placed beside the Basic files, e.g. `MyBasic.yaml`, `MyBasic.xlf` and `de.MyBasic.xlf` or there could be a directory for each Basic like it is for content blocks with `Source/Language` sub folders.

**Comment by nhovratov** [comment]
Right now Basics are just a "find and replace" pattern. They are loaded early into your Content Block and treated as if you have written it yourself there. This means if you leave out `label` in the Basic, you can set it via `Labels.xlf` in your Content Block. I guess you would want to avoid this redundancy by defining standard labels for your Basics. Could be an interesting feature, need to think and discuss about with the team.

**Comment by nhovratov** [comment]
We discussed it with the team. We won't work on this feature. The first reason is technical nature as described above. Content Blocks has no knowledge about Basics in later states of processing. So it is not possible to have a separate Labels.xlf for basics. Second reason is that Basics are a global set of fields and the labels should be defined globally as well in the host extension. So there is no other way but to define full LLL:EXT paths. We will document this in the basics article.
