### ISSUE TITLE
[FEATURE] PageType automatic -hideinmenu icon registration

### ISSUE THREAD

**Issue by ogrosko** [FriendsOfTYPO3/content-blocks#92]
Hello,
For better UX it would be fine to register PageType `Icon-hideinmenu.svg` automatically. See core config [here](https://github.com/TYPO3/typo3/blob/main/typo3/sysext/core/Configuration/TCA/pages.php#L32)
I would recommend to check for file existence in `Assets/Icon-hideinmenu.svg` folder and add desired config.

What do you think?

**Comment by nhovratov** [comment]
Oh, yes this would be a great improvement! Actually it would be even better if TYPO3 would add opacity to the element as fallback, instead of showing the default page icon.

**Comment by ogrosko** [comment]
Yes, it would be nice to have such a feature in Typo3 core, but I don't think something is planned right now ... 😞 
If you point me to the right code place I'm happy to implement it 😉

**Comment by nhovratov** [comment]
Well, we can make changes to the Core if we need them. Let me check it first.
