### ISSUE TITLE
Variables in CSS und JS assets?

### ISSUE THREAD

**Issue by wowaTYPO3** [FriendsOfTYPO3/content-blocks#96]
Is it possible, to use variables like {data.variablename} in the Frontend.css and/or Frontend.js?
Seems not to work at the moment.

**Comment by nhovratov** [comment]
This does only work in Fluid. If you need variables in CSS/Js you can use the Assets ViewHelper like so:

<cb:asset.css identifier="abc">
   {data.variablename}
</cb.asset.css>

**Comment by wowaTYPO3** [comment]
Arrgg, thank you. Sure. I should have thought of that myself.

**Comment by hilburger** [comment]
> This does only work in Fluid. If you need variables in CSS/Js you can use the Assets ViewHelper like so:
> 
> <cb:asset.css identifier="abc"> {data.variablename} </cb.asset.css>

I'd really like to use this but I don't know where to put what. Could you give a short example? 
That would be awesome! Thank you :)

**Comment by jonaseberle** [comment]
@hilburger that goes into the `Frontend.html` (works in `EditorPreview.html` as well because the AssetViewHelpers are awesome).

For inline defined assets you should use the **Core** `f:asset.css/script` ViewHelpers (our ViewHelpers do not support inline defined I just realized).

Here's an example: https://github.com/nhovratov/content-blocks/blob/main/Build/content-blocks-examples/ContentBlocks/ContentElements/cta/Source/Frontend.html

**Comment by hilburger** [comment]
> @hilburger that goes into the `Frontend.html` (works in `EditorPreview.html` as well because the AssetViewHelpers are awesome).
> 
> For inline defined assets you should use the **Core** `f:asset.css/script` ViewHelpers (our ViewHelpers do not support inline defined I just realized).
> 
> Here's an example: https://github.com/nhovratov/content-blocks/blob/main/Build/content-blocks-examples/ContentBlocks/ContentElements/cta/Source/Frontend.html

@jonaseberle 

Thank you for the example. Somehow I can't get it to work, although trying to adopt your code in your Frontend.html. 
Can you spot my mistake? 

```html
<html
        xmlns:f="http://typo3.org/ns/TYPO3/CMS/Fluid/ViewHelpers"
        xmlns:cb="http://typo3.org/ns/TYPO3/CMS/ContentBlocks/ViewHelpers"
        data-namespace-typo3-fluid="true"
>

<f:layout name="Default"/>
<f:section name="Header"/>

<f:section name="Main">

<cb:asset.css identifier="content-block-css-tnt-digital-tnt-digital/3js-viewer" file="Frontend.css"/>
<cb:asset.script identifier="content-block-js-tnt-digital-tnt-digital/3js-viewer" file="Frontend.js"/>
<!--
Frontend template for Content Block: tnt-digital/3js-viewer<br>
Header: {data.header}<br>
Pfad: {data._raw.tntdigital_3jsviewer_folder}<br>
Page-ID: {data.uid}-->
<f:for each="{data.folder}" as="item">
    <f:if condition="{item.properties.extension} == 'js'">
        <!--
        Path: /fileadmin{item.identifier}
        Data-ID: {data.uid}
        Ext:  {item.properties.extension}
        -->

        <f:variable name="backgroundUrl">backgroundUrl</f:variable>
        <f:variable name="elementBgId">Foo-{data.uid}</f:variable>
        <f:variable name="backgroundImageStyles">bar-{data.uid}</f:variable>
        <f:asset.css identifier="bar-{data.uid}">
            #{backgroundImageStyles -> f:format.raw()}
        </f:asset.css>
        <div class="Foo" id="{elementBgId}"></div>

        <!-- Ignore for testing of handling variable over to Frontens.css and .js files -->
        <canvas id="canvasId{data.uid}" class="webgl" data-name="{item.identifier}" data-canvas-id="canvasId{item.uid}"></canvas>
        <script type="module" src="/fileadmin{item.identifier}"></script>
    </f:if>
</f:for>

</f:section>

</html>
```

**Comment by hilburger** [comment]
**PS.** I'm on TYPO3 12 latest and content_blocks (contentblocks/content-blocks) 0.7 latest.

**Comment by jonaseberle** [comment]
@hilburger can you simplify please to get to a [MRE](https://en.wikipedia.org/wiki/Minimal_reproducible_example)?
Remove the `<for>` loop and `<if>` please. What does the HTML output of that <style> tag look like then?

You can try with something obvious and silly like 
```html
  <f:asset.css identifier="inline CSS with Fluid vars">
    div::before {
      display: block;
      content: '{data.uid}';
    }
  </f:asset.css>
```

**Comment by hilburger** [comment]
> @hilburger can you simplify please to get to a [MRE](https://en.wikipedia.org/wiki/Minimal_reproducible_example)? Remove the `<for>` loop and `<if>` please. What does the HTML output of that <style> tag look like then?
> 
> You can try with something obvious and silly like
> 
> ```
>   <f:asset.css identifier="inline CSS with Fluid vars">
>     div::before {
>       display: block;
>       content: '{data.uid}';
>     }
>   </f:asset.css>
> ```

@jonaseberle 
The code looks like this now: 
```html
<html
        xmlns:f="http://typo3.org/ns/TYPO3/CMS/Fluid/ViewHelpers"
        xmlns:cb="http://typo3.org/ns/TYPO3/CMS/ContentBlocks/ViewHelpers"
        data-namespace-typo3-fluid="true"
>

<f:layout name="Default"/>
<f:section name="Header"/>

<f:section name="Main">

<cb:asset.css identifier="content-block-css-tnt-digital-tnt-digital/3js-viewer" file="Frontend.css"/>
<cb:asset.script identifier="content-block-js-tnt-digital-tnt-digital/3js-viewer" file="Frontend.js"/>
<!--
Frontend template for Content Block: tnt-digital/3js-viewer<br>
Header: {data.header}<br>
Pfad: {data._raw.tntdigital_3jsviewer_folder}<br>
Page-ID: {data.uid}-->
    <f:asset.css identifier="inline CSS with Fluid vars">
        div::before {
        display: block;
        content: '{data.uid}';
        }
    </f:asset.css>
</f:section>

</html>
```
and the result is that the uid is added inline before all DIVs. The Frontend.css remains untouched.

![image](https://github.com/user-attachments/assets/403676ae-0a98-4c87-a2a1-f45b47550a92)

**Comment by jonaseberle** [comment]
Good, so it works. You can take it from here ;)

**Comment by hilburger** [comment]
> This does only work in Fluid. If you need variables in CSS/Js you can use the Assets ViewHelper like so:
> 
> <cb:asset.css identifier="abc"> {data.variablename} </cb.asset.css>

@jonaseberle 
So I understand you correctly now that it is only possible to add/pass/insert Fluid variables inline but not into the Frontend.js/.css files? 
Have I misunderstood your reply to Wolfgang?
Sorry for stupid questions and stealing your time, by the way! 

```html
<html
        xmlns:f="http://typo3.org/ns/TYPO3/CMS/Fluid/ViewHelpers"
        xmlns:cb="http://typo3.org/ns/TYPO3/CMS/ContentBlocks/ViewHelpers"
        data-namespace-typo3-fluid="true"
>

<f:layout name="Default"/>
<f:section name="Header"/>
<f:section name="Main">

    <!-- Version 1: Add/passing over to Frontend.js/.css - Not working -->
    
    <cb:asset.script identifier="cb-js" file="Frontend.js">
        console.log('cb:asset.script: {data.uid}');
        const testCB = 'cb:asset.script: {data.uid}';
    </cb:asset.script>
    <cb:asset.css identifier="cb-css" file="Frontend.css">
        div::after {
        display: block;
        content: 'cb:asset.css {data.uid}';
        }
    </cb:asset.css>

    <!-- Version 2: Adding inline - Working -->

    <f:asset.script identifier="f-js">
        console.log('f:asset.script: {data.uid}');
        const testF = 'f:asset.script: {data.uid}';
    </f:asset.script>
    <f:asset.css identifier="f-css">
        div::before {
        display: block;
        content: 'f.asset.css: {data.uid}';
        }
    </f:asset.css>
</f:section>
</html>
```

**Comment by jonaseberle** [comment]
yes

**Comment by hilburger** [comment]
Alright, thank you!
