### ISSUE TITLE
Add a way to sort Content Elements in ContentElementWizard group

### ISSUE THREAD

**Issue by PLACEBOBRO** [FriendsOfTYPO3/content-blocks#99]
It is possible to group your content elements via e.g. "group: common" to add elements to the common group. Unfortunately I didn't find a way to sort the created elements inside the group.
For example if i want the "Akkordeon" content element on the first position, it is not possible.
![image](https://github.com/nhovratov/content-blocks/assets/40799248/10fed08c-1478-4588-84b5-a059c1fb61ac)

Do you know a workaround? I tried the "old" method below, but didn't work out as expected. 
`mod.wizards.newContentElement.wizardItems.common.show = accordion`

System is TYPO3 12.4.9, with Content Blocks 0.3.0

**Comment by nhovratov** [comment]
@PLACEBOBRO Have a look here: https://docs.typo3.org/p/contentblocks/content-blocks/main/en-us/YamlReference/Root/Index.html#confval-priority

We have introduced the `priority` pattern.

**Comment by PLACEBOBRO** [comment]
Woah that was fast. This solves my issue. Thank you very much!
